### ISSUE TITLE
Support for kernel 5.18

### ISSUE THREAD

**Issue by sirlucjan** [smuellerDD/lrng#10]
Do you plan to add support for kernel 5.18? Thanks for your work so far!

**Comment by smuellerDD** [comment]
Am Dienstag, 10. Mai 2022, 10:11:24 CEST schrieb Piotr Górski:

Hi Piotr,

> Do you plan to add support for kernel 5.18? Thanks for your work so far!

Yes, it is already on my laptop - including significant improvements and a new 
optional entropy source.


Ciao
Stephan

**Comment by sirlucjan** [comment]
Great, can't wait.
