### ISSUE TITLE
Rebase due to v5.18.1 incompatibility

### ISSUE THREAD

**Issue by sirlucjan** [smuellerDD/lrng#11]
Hi,

Could you please update LRNG - with the release of kernel 5.18.1 (changes in drivers/char/random) LRNG stopped working. Thank you in advance!

@pfactum Could you please confirm?

**Comment by ptr1337** [comment]
I can confirm that also, probably due the big changes in random.c. 

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/drivers/char/random.c?id=v5.18.1&id2=v5.18

**Comment by smuellerDD** [comment]
Am Montag, 30. Mai 2022, 18:17:35 CEST schrieb ptr1337:

Hi ptr1337,

> I can confirm that also, probably due the big changes in random.c.
> 
> https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/driver
> s/char/random.c?id=v5.18.1&id2=v5.18

I wish you are kidding me - such massive changes in a stable kernel? 
Seriously?

Anyways, I will have a look.

Thanks for pointing me to this.

Ciao
Stephan

**Comment by pfactum** [comment]
@smuellerDD no kidding unfortunately :(, and thanks in advance for looking into this.

**Comment by smuellerDD** [comment]
Am Montag, 30. Mai 2022, 19:50:55 CEST schrieb Oleksandr Natalenko:

Hi Oleksandr,

> @smuellerDD no kidding unfortunately :(, and thanks in advance for looking
> into this.

Unbelievable such changes in an alleged stable kernel.

Anyhow, please pull the updates. I only updated the C files for now and not 
the patches as I would like to wait for potential more changes over the next 
few "stable" releases.

Can you please try the updates?

Ciao
Stephan

**Comment by sirlucjan** [comment]
I have prepared a patch that will allow you to make revisions:

https://github.com/sirlucjan/kernel-patches/blob/master/5.18/lrng-patches-v2-sep/0027-lrng-5.18-update-to-the-latest-git-HEAD.patch

However, I can let you know tomorrow at the earliest.

**Comment by pfactum** [comment]
> Can you please try the updates?

Builds and boots fine for me, than you.

**Comment by sirlucjan** [comment]
@xanmod Alexandre, it looks like LRNG is working again.

**Comment by smuellerDD** [comment]
Am Montag, 30. Mai 2022, 22:15:01 CEST schrieb Piotr Górski:

Hi Piotr,

> I have prepared a patch that will allow you to make revisions:
> 
> https://github.com/sirlucjan/kernel-patches/blob/master/5.18/lrng-patches-v2
> -sep/0027-lrng-5.18-update-to-the-latest-git-HEAD.patch
> 
> However, I can let you know tomorrow at the earliest.

Thanks for the hint that I could simply take 2 patches and form it into a 
"forward-patch". Thus I took the liberty to simply do a git format-patch and 
add the 2 patches into the repo as part of the "backport" patch directory.

Thanks

Ciao
Stephan

**Comment by sirlucjan** [comment]
The problem seems to have been solved. Thanks a lot!

**Comment by Vladdrako** [comment]
@smuellerDD Update 5.15 patches too, please.

**Comment by sirlucjan** [comment]
Probably exactly the same as in 5.18 - changes in drivers/char/random.c

**Comment by smuellerDD** [comment]
Am Dienstag, 31. Mai 2022, 14:02:39 CEST schrieb Piotr Górski:

Hi Piotr,

> Probably exactly the same as in 5.18 - changes in drivers/char/random.c

Can you point me to the 5.15 version you are seeing the issues with? Using 
5.15.0 all was good.

Ciao
Stephan

**Comment by Vladdrako** [comment]
> What issues do you see with 5.15?

5.15.44 provides massive rng refactoring. So, lrng didn't compile anymore. Also, patches from backports and kernel_patches folders are conflicted. Probably because in kernel_patches v43, in backports v45.

**Comment by smuellerDD** [comment]
Am Dienstag, 31. Mai 2022, 15:02:27 CEST schrieb Vladdrako:

Hi Vladdrako,

> > What issues do you see with 5.15?
> 
> 5.15.44 provides massive rng refactoring. So, lrng didn't compile anymore.
> Also, patches from backports and kernel_patches folders are conflicted.
> Probably because in kernel_patches v43, in backports v45.

Oh my. Shaking my head. Thanks for the reference. I will take a look.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, 31. Mai 2022, 15:02:27 CEST schrieb Vladdrako:

Hi Vladdrako,

> > What issues do you see with 5.15?
> 
> 5.15.44 provides massive rng refactoring. So, lrng didn't compile anymore.
> Also, patches from backports and kernel_patches folders are conflicted.
> Probably because in kernel_patches v43, in backports v45.

The culprit was the same changes applicable to 5.18.1 are now needed for 
5.15.44.

The provided updated patch should do it.

Ciao
Stephan
