### ISSUE TITLE
Will the 5.18.4 update affect LRNG?

### ISSUE THREAD

**Issue by sirlucjan** [smuellerDD/lrng#13]
There are several patches lined up for 5.18.4 that could potentially affect LRNG. Could you take a look at them? If affected, I'd be happy to test the patch. 

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/5.18

**Comment by sirlucjan** [comment]
I am most suspicious of this commit. I hope completely wrong :)

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/commit/?h=queue/5.18&id=c7d1f88e90bec7ca3804aa1dd2180f7d65b071d3

**Comment by sirlucjan** [comment]
I suspect that in theory a simple change like this, similar to the upstream, might be enough.

https://github.com/sirlucjan/kernel-patches/blob/master/5.18/lrng-patches-v5-sep/0030-lrng-5.18-drop-EXPORT_SYMBOL_GPL-add_bootloader_rand.patch

**Comment by ptr1337** [comment]
I did right now a compile with your lrng patch and the 5.18.4 rc1 and it seems fine so far, booted without problems. 
dmesg does also not report anything, lrmg has been loaded.

**Comment by sirlucjan** [comment]
Thank you very much for feedback!

**Comment by smuellerDD** [comment]
Am Montag, 13. Juni 2022, 12:32:58 CEST schrieb Piotr Górski:

Hi Piotr,

> I am most suspicious of this commit. I hope completely wrong :)
> 
> https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/c
> ommit/?h=queue/5.18&id=c7d1f88e90bec7ca3804aa1dd2180f7d65b071d3

Why are you suspicious here?

Ciao
Stephan

**Comment by sirlucjan** [comment]
It looks like all is well and my patch is not needed - I will let you know if it is.
