### ISSUE TITLE
Compilation error with latest commits

### ISSUE THREAD

**Issue by sirlucjan** [smuellerDD/lrng#15]
@smuellerDD  The latest commits cause this error:

``` GEN     .version
  CHK     include/generated/compile.h
  LD      vmlinux.o
  OBJTOOL vmlinux.o
vmlinux.o: warning: objtool: smack_inode_setsecurity.cold()+0x11: relocation to !ENDBR: smack_inode_setsecurity()+0x16f
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  CC      .vmlinux.export.c
  LD      .tmp_vmlinux.btf
ld: vmlinux.o: in function `lrng_proc_type_show':
/home/lucjan/Pracownia/Repo/kernel/linux/rolling/linux-lucjan-git/src/linux/drivers/char/lrng/lrng_proc.c:45: undefined reference to `lrng_ntg1_compliant'
ld: vmlinux.o: in function `prandom_init_late':
/home/lucjan/Pracownia/Repo/kernel/linux/rolling/linux-lucjan-git/src/linux/lib/random32.c:625: undefined reference to `register_random_ready_notifier'
ld: vmlinux.o: in function `initialize_ptr_random':
/home/lucjan/Pracownia/Repo/kernel/linux/rolling/linux-lucjan-git/src/linux/lib/vsprintf.c:808: undefined reference to `get_random_bytes_arch'
ld: /home/lucjan/Pracownia/Repo/kernel/linux/rolling/linux-lucjan-git/src/linux/lib/vsprintf.c:813: undefined reference to `register_random_ready_notifier'
  BTF     .btf.vmlinux.bin.o
pahole: .tmp_vmlinux.btf: No such file or directory
  LD      .tmp_vmlinux.kallsyms1
.btf.vmlinux.bin.o: file not recognized: file format not recognized
```

Is this for kernel 5.18 or already for 5.19?

**Comment by smuellerDD** [comment]
Am Freitag, 24. Juni 2022, 23:01:55 CEST schrieb Piotr Górski:

Hi Piotr,

> The latest commits cause this error:
> 
> ``` GEN     .version
>   CHK     include/generated/compile.h
>   LD      vmlinux.o
>   OBJTOOL vmlinux.o
> vmlinux.o: warning: objtool: smack_inode_setsecurity.cold()+0x11: relocation
> to !ENDBR: smack_inode_setsecurity()+0x16f MODPOST vmlinux.symvers
>   MODINFO modules.builtin.modinfo
>   GEN     modules.builtin
>   CC      .vmlinux.export.c
>   LD      .tmp_vmlinux.btf
> ld: vmlinux.o: in function `lrng_proc_type_show':
> /home/lucjan/Pracownia/Repo/kernel/linux/rolling/linux-lucjan-git/src/linux/
> drivers/char/lrng/lrng_proc.c:45: undefined reference to
> `lrng_ntg1_compliant' ld: vmlinux.o: in function `prandom_init_late':
> /home/lucjan/Pracownia/Repo/kernel/linux/rolling/linux-lucjan-git/src/linux/
> lib/random32.c:625: undefined reference to `register_random_ready_notifier'
> ld: vmlinux.o: in function `initialize_ptr_random':
> /home/lucjan/Pracownia/Repo/kernel/linux/rolling/linux-lucjan-git/src/linux/
> lib/vsprintf.c:808: undefined reference to `get_random_bytes_arch' ld:
> /home/lucjan/Pracownia/Repo/kernel/linux/rolling/linux-lucjan-git/src/linux
> /lib/vsprintf.c:813: undefined reference to `register_random_ready_notifier'
> BTF     .btf.vmlinux.bin.o
> pahole: .tmp_vmlinux.btf: No such file or directory
>   LD      .tmp_vmlinux.kallsyms1
> .btf.vmlinux.bin.o: file not recognized: file format not recognized
> ```
> 
> Is this for kernel 5.18 or already for 5.19?

Yes, I am using head to develop for the current upstream development version. 
And head is not subject to all tests all the time. Just yesterday I had to 
revert 2 patches where my stress testing showed that there was a locking 
issue.

Should I start using branches to identify the different kernel versions? I.e. 
v45 is intended for 5.18. I could use kernel version references instead of 
these arbitrary version numbers to make the relationship better. And if there 
is a fix that should go into the older version.

With such branches you could then base your kernel versions on these branches.


Ciao
Stephan

**Comment by sirlucjan** [comment]
That sounds good and I think that is the best solution. Separate branches for each kernel version will make everything much easier.

**Comment by smuellerDD** [comment]
Am Samstag, 25. Juni 2022, 11:45:45 CEST schrieb Piotr Górski:

Hi Piotr,

> That sounds good and I think that is the best solution. Separate branches
> for each kernel version will make everything much easier.

I added a branch 5.18 and merged the code there that should be applicable to 
5.18. I hope this helps?

Ciao
Stephan

**Comment by sirlucjan** [comment]
Yes, that will be helpful. Thanks.

**Comment by sirlucjan** [comment]
Commit https://github.com/smuellerDD/lrng/commit/89b7f953a02d6da69f745904c007d857f6ec5ff4 is broken. 

```
vmlinux.o: warning: objtool: smack_inode_setsecurity.cold()+0x11: relocation to !ENDBR: smack_inode_setsecurity()+0x16f
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  CC      .vmlinux.export.c
  LD      .tmp_vmlinux.btf
ld: vmlinux.o: in function `lrng_proc_type_show':
/home/lucjan/Pobrane/linux-lucjan/src/linux-5.18.6/drivers/char/lrng/lrng_proc.c:45: undefined reference to `lrng_ntg1_compliant'
  BTF     .btf.vmlinux.bin.o
pahole: .tmp_vmlinux.btf: No such file or directory
  LD      .tmp_vmlinux.kallsyms1
.btf.vmlinux.bin.o: file not recognized: file format not recognized
```

**Comment by ptr1337** [comment]
> Commit [89b7f95](https://github.com/smuellerDD/lrng/commit/89b7f953a02d6da69f745904c007d857f6ec5ff4) is broken.
> 
> ```
> vmlinux.o: warning: objtool: smack_inode_setsecurity.cold()+0x11: relocation to !ENDBR: smack_inode_setsecurity()+0x16f
>   MODPOST vmlinux.symvers
>   MODINFO modules.builtin.modinfo
>   GEN     modules.builtin
>   CC      .vmlinux.export.c
>   LD      .tmp_vmlinux.btf
> ld: vmlinux.o: in function `lrng_proc_type_show':
> /home/lucjan/Pobrane/linux-lucjan/src/linux-5.18.6/drivers/char/lrng/lrng_proc.c:45: undefined reference to `lrng_ntg1_compliant'
>   BTF     .btf.vmlinux.bin.o
> pahole: .tmp_vmlinux.btf: No such file or directory
>   LD      .tmp_vmlinux.kallsyms1
> .btf.vmlinux.bin.o: file not recognized: file format not recognized
> ```
> 
> I don't know if this has to do with the fact that there have been changes in 5.19 or if there is just some declaration missing.

Did merged them also and faced the same issue. So can confirm that.

Here the diff:

https://github.com/ptr1337/kernel-patches/commit/721dd2fea9e4d7f08fbf8335831dbd30b2dfd54d

**Comment by smuellerDD** [comment]
Am Samstag, 25. Juni 2022, 16:20:02 CEST schrieb ptr1337:

Hi ptr1337,

Apologies, somehow the revert messed up this patch set. It is fixed now.

> > Commit
> > [89b7f95](https://github.com/smuellerDD/lrng/commit/89b7f953a02d6da69f745
> > 904c007d857f6ec5ff4) is broken.
> > 
> > ```
> > vmlinux.o: warning: objtool: smack_inode_setsecurity.cold()+0x11:
> > relocation to !ENDBR: smack_inode_setsecurity()+0x16f> 
> >   MODPOST vmlinux.symvers
> >   MODINFO modules.builtin.modinfo
> >   GEN     modules.builtin
> >   CC      .vmlinux.export.c
> >   LD      .tmp_vmlinux.btf
> > 
> > ld: vmlinux.o: in function `lrng_proc_type_show':
> > /home/lucjan/Pobrane/linux-lucjan/src/linux-5.18.6/drivers/char/lrng/lrng_
> > proc.c:45: undefined reference to `lrng_ntg1_compliant'> 
> >   BTF     .btf.vmlinux.bin.o
> > 
> > pahole: .tmp_vmlinux.btf: No such file or directory
> > 
> >   LD      .tmp_vmlinux.kallsyms1
> > 
> > .btf.vmlinux.bin.o: file not recognized: file format not recognized
> > ```
> > 
> > I don't know if this has to do with the fact that there have been changes
> > in 5.19 or if there is just some declaration missing.
> Did merged them also and faced the same issue. So can confirm that.
> 
> Here the diff:
> 
> https://github.com/ptr1337/kernel-patches/commit/721dd2fea9e4d7f08fbf8335831
> dbd30b2dfd54d


Ciao
Stephan

**Comment by sirlucjan** [comment]
I'll let you know later if everything works. @ptr1337 Unless you manage to do it sooner. I'm about to go cool off in this infernal heat with a cold beer. Cheers :)

**Comment by ptr1337** [comment]
Compiled fine on 5.18.7 with LLVM thinlto used. 
Much thanks for your work @smuellerDD !

Regards.

**Comment by smuellerDD** [comment]
Am Samstag, 25. Juni 2022, 19:09:05 CEST schrieb ptr1337:

Hi ptr1337,

> Compiled fine on 5.18.7 with LLVM thinlto used.
> Much thanks for your work @smuellerDD !
> 
> Regards.

Thanks a lot for your testing. I will start maintaining now such branches for 
the main kernel versions. Yet, I hope that within a main kernel version there 
is not going to be kernel-internal API incompatible changes (like between 5.18 
and 5.18.1). 


Ciao
Stephan

**Comment by sirlucjan** [comment]
Also I can confirm that everything works perfectly.

**Comment by smuellerDD** [comment]
Am Sonntag, 26. Juni 2022, 14:18:39 CEST schrieb Piotr Górski:

Hi Piotr,

> Also I can confirm that everything works perfectly.

Thank you for the confirmation.

Abeit I test all changes and patches, somehow the one missing hunk was not 
applied and had to be applied separately.

Ciao
Stephan

**Comment by ptr1337** [comment]
Hey @smuellerDD ,

me and @sirlucjan sorted with lrng agaom a upsteam commit out.

Again some upstream comits which affect lrng. It wont affect the compilation, but modpost will complain about removing the export SYMBOL.

Actually that commit fixes the warning message which comes as soon the vmlinuz gets linked:
https://github.com/ptr1337/kernel-patches/commit/3a95d9d644cb7781736500330b3e6cc3ec39116c#diff-cfbd96da77bcd7f9024408f7715f08fcb8ccac3df6b12b1e8108b1c07efec13dL7463

upstream commit:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/commit/?h=linux-5.18.y&id=7f4bdaf8cb227241a87430dd1ffec96e4eb7d5e7

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. Juni 2022, 01:54:55 CEST schrieb ptr1337:

Hi ptr1337,

> Hey @smuellerDD ,
> 
> me and @sirlucjan sorted with lrng agaom a upsteam commit out.
> 
> Again some upstream comits which affect lrng. It wont affect the
> compilation, but modpost will complain about removing the export SYMBOL.
> 
> Actually that commit fixes the warning message which comes as soon the
> vmlinuz gets linked:
> https://github.com/ptr1337/kernel-patches/commit/3a95d9d644cb7781736500330b
> 3e6cc3ec39116c#diff-cfbd96da77bcd7f9024408f7715f08fcb8ccac3df6b12b1e8108b1c0
> 7efec13dL7463
> 
> upstream commit:
> 
> https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/c
> ommit/?h=linux-5.18.y&id=7f4bdaf8cb227241a87430dd1ffec96e4eb7d5e7

I have pushed a change to fix this.

Thanks!


Ciao
Stephan
