### ISSUE TITLE
[not an issue]Backport patches from master to 5.18

### ISSUE THREAD

**Issue by sirlucjan** [smuellerDD/lrng#16]
Latest patches from master branch work with kernel 5.18 without any problem. We have checked it together with @ptr1337

I am thinking of the following fixes: 

```8af92f0 (HEAD -> master, upstream/master, origin/master, origin/HEAD) lrng: prediction resistance - add pool lock
1606867 lrng: O_SYNC - allow DRBG to be used as conditioning component
e3a53de test: update due to NTG.1 marker
0857e23 lrng: sched ES - use per-cpu compression hash
6e23023 test: sudo is not required for stress testing
1919e5e lrng: editorial changes
```
I think @ptr1337 would agree with me that these can be easily merged into the 5.18 branch.
Let me keep this thread open and we will report to you which patches work well with the currently stable kernel version.

**Comment by ptr1337** [comment]
Yes, did compiled linux 5.18.8. Everything seems fine. dmesg does not report anything. booted without issues.

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. Juni 2022, 14:58:50 CEST schrieb ptr1337:

Hi ptr1337,

> Yes, did compiled linux 5.18.8. Everything seems fine. dmesg does not report
> anything. booted without issues.

Thanks a lot for your report and testing - I will cherry-pick them tomorrow, 
although I would like to let the sched ES update sit in master for a bit 
longer. This is a core change in the heart of one entropy source and it needs 
to be done right. Thus I plan to review it once again with additional testing 
and measurements before pushing it to the 5.18 branch.

My approach is that the master branch is my "playground" which may not yet 
have recevied complete testing. The branches like 5.18 are considered 
production-ready branches.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. Juni 2022, 14:58:50 CEST schrieb ptr1337:

Hi ptr1337,

> Yes, did compiled linux 5.18.8. Everything seems fine. dmesg does not report
> anything. booted without issues.

If you are interested, I can give you a short introduction how to conduct the 
functional testing of the LRNG patch series. The testing is fully automated 
and should cover all functional aspects of the LRNG.

The easiest test that requires no setup which usually reveals many issues is 
the stress tester provided in test/swap_stress.sh. If you have compiled the 
following options, then you can simply start the stress tester which executes 
5000 rounds and must complete without any issue:

CONFIG_LRNG_SWITCH=y
CONFIG_LRNG_SWITCH_HASH=y
CONFIG_LRNG_HASH_KCAPI=m
CONFIG_LRNG_SWITCH_DRNG=y
CONFIG_LRNG_SWITCH_DRBG=m
CONFIG_LRNG_SWITCH_DRNG_KCAPI=m

I use the stress tester as my smoke test for every patch.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. Juni 2022, 14:56:49 CEST schrieb Piotr Górski:

Hi Piotr,

> Latest patches from master branch work with kernel 5.18 without any problem.
> We have checked it together with @ptr1337
> 
> I am thinking of the following fixes:
> 
> ```8af92f0 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
> lrng: prediction resistance - add pool lock 1606867 lrng: O_SYNC - allow
> DRBG to be used as conditioning component

pushed

> e3a53de test: update due to NTG.1
> marker

pushed

> 0857e23 lrng: sched ES - use per-cpu compression hash

not pushed yet as mentioned

> 6e23023 test: sudo is not required for stress testing

pushed

> 1919e5e lrng: editorial changes

pushed

> ```
> I think @ptr1337 would agree with me that these can be easily merged into
> the 5.18 branch.

I also pushed additional cleanups I just tested with 5.18.8 as well.


Ciao
Stephan

**Comment by ptr1337** [comment]
> Am Mittwoch, 29. Juni 2022, 14:58:50 CEST schrieb ptr1337: Hi ptr1337,
> Yes, did compiled linux 5.18.8. Everything seems fine. dmesg does not report anything. booted without issues.
> If you are interested, I can give you a short introduction how to conduct the functional testing of the LRNG patch series. The testing is fully automated and should cover all functional aspects of the LRNG. The easiest test that requires no setup which usually reveals many issues is the stress tester provided in test/swap_stress.sh.

Thanks for your explanation. I will definitely do this as soon I have some time for!

**Comment by smuellerDD** [comment]
I think this issue can be closed now. If you think there is still an issue, please reopen. Thanks.
