### ISSUE TITLE
Backport patches for lower version LTS kernels

### ISSUE THREAD

**Issue by atndko** [smuellerDD/lrng#17]
random.c and related changes had been ported into latest 4.9.320, 4.14.285, 4.19.249, previous 5.4.200 and 5.10, will you provide new backport patches? Thank you.

**Comment by smuellerDD** [comment]
Am Samstag, 2. Juli 2022, 10:43:24 CEST schrieb Neptune:

Hi Neptune,

> random.c and related changes had been ported into latest 4.9.320, 4.14.285,
> 4.19.249, previous 5.4.200 and 5.10, will you provide new backport patches?
> Thank you.

Yes, I will see that patches for those LTS kernels are made available.

Ciao
Stephan
