### ISSUE TITLE
6.0 patches miss lrng_get_seed() declaration

### ISSUE THREAD

**Issue by pfactum** [smuellerDD/lrng#18]
Hello.

6.0 patches (_maybe, others too, but I've checked 6.0 only_) miss `lrng_get_seed()` bits from `lrng.h`, so I had to pick them from the `lrng.h` file in the root folder of the repo directly: https://codeberg.org/pf-kernel/linux/commit/a1f679e18f4f40fc55efedc68b0f35dc47d676c1

Could you please check this?

Thanks.

**Comment by smuellerDD** [comment]
Thanks for catching that so fast. The lrng.h in the patch set is now consistent with the code repository.
