### ISSUE TITLE
Missing lrng patches for Linux kernel v4.19

### ISSUE THREAD

**Issue by jetm** [smuellerDD/lrng#2]
I noticed it's missing the patches for Linux kernel LTS v4.19. 

Is there a particular reason why there are not patches for v4.19 LTS?

The lrng v4.20 patches apply OK on Linux kernel v4.19.

**Comment by smuellerDD** [comment]
Am Freitag, 10. Juli 2020, 20:16:26 CEST schrieb Javier Tiá:

Hi Javier,

> I noticed it's missing the patches for Linux kernel LTS v4.19.
> 
> Is there a particular reason why there are not patches for v4.19 LTS?
> 
> The lrng v4.20 patches apply OK on a Linux kernel v4.19.

There is no particular reason. I have the patches as I fed them to the LKML. I 
hope that my patch series would be taken at some point considering it is a 
full drop-in replacement.

That said, there is no particular reason why I do not have a 4.19 patch set.

Ciao
Stephan
