### ISSUE TITLE
Adopt v6.2 changes

### ISSUE THREAD

**Issue by pfactum** [smuellerDD/lrng#22]
Hello.

With v6.2-rc1 release there's 2c03e16f44993d45f064580adb0eb408b513ad72 ("random: remove early archrandom abstraction"), which removes `arch_get_random_seed_longs_early()` and `arch_get_random_longs_early()`, which makes my build fail:

```
[  683s] drivers/char/lrng/lrng_es_mgr.c: In function 'lrng_rand_initialize_early':
[  683s] drivers/char/lrng/lrng_es_mgr.c:382:25: error: implicit declaration of function 'arch_get_random_seed_longs_early' [-Werror=implicit-function-declaration]
[  683s]   382 |                 longs = arch_get_random_seed_longs_early(seed.data + i,
[  683s]       |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  684s] drivers/char/lrng/lrng_es_mgr.c:386:25: error: implicit declaration of function 'arch_get_random_longs_early' [-Werror=implicit-function-declaration]
[  684s]   386 |                 longs = arch_get_random_longs_early(seed.data + i,
[  684s]       |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

You may want to adopt corresponding changes.

Thank you.

**Comment by pfactum** [comment]
Testing this now:

```
commit 9e4e4cfabcd7a64633b72d3b109f12250f644f9d
Author: Oleksandr Natalenko <oleksandr@natalenko.name>
Date:   Mon Dec 26 21:10:58 2022 +0100

    lrng-6.2: adopt 2c03e16f4499
    
    Signed-off-by: Oleksandr Natalenko <oleksandr@natalenko.name>

diff --git a/drivers/char/lrng/lrng_es_mgr.c b/drivers/char/lrng/lrng_es_mgr.c
index 5d1ab84c97cb..2bcc7c9246e3 100644
--- a/drivers/char/lrng/lrng_es_mgr.c
+++ b/drivers/char/lrng/lrng_es_mgr.c
@@ -379,11 +379,11 @@ void __init lrng_rand_initialize_early(void)
 	unsigned int i;
 
 	for (i = 0; i < ARRAY_SIZE(seed.data); i += longs) {
-		longs = arch_get_random_seed_longs_early(seed.data + i,
+		longs = arch_get_random_seed_longs(seed.data + i,
 						ARRAY_SIZE(seed.data) - i);
 		if (longs)
 			continue;
-		longs = arch_get_random_longs_early(seed.data + i,
+		longs = arch_get_random_longs(seed.data + i,
 						    ARRAY_SIZE(seed.data) - i);
 		if (longs)
 			continue;
```

**Comment by pfactum** [comment]
Another change that should be accounted for: db516da95ce458f0cab5e7ae2db93fd821484d7d ("hw_random: use add_hwgenerator_randomness() for early entropy").

**Comment by pfactum** [comment]
It looks like e9a688bcb19348862afe30d7c85bc37c4c293471 ("random: use rejection sampling for uniform bounded random integers") must be taken into account too, otherwise the following build error occurs:

```
[ 2148s]   MODPOST Module.symvers
[ 2162s] ERROR: modpost: "__get_random_u32_below" [fs/ext4/ext4.ko] undefined!
[ 2162s] ERROR: modpost: "__get_random_u32_below" [fs/ubifs/ubifs.ko] undefined!
[ 2162s] ERROR: modpost: "__get_random_u32_below" [fs/f2fs/f2fs.ko] undefined!
[ 2162s] ERROR: modpost: "__get_random_u32_below" [fs/ceph/ceph.ko] undefined!
[ 2162s] ERROR: modpost: "__get_random_u32_below" [drivers/gpu/drm/i915/i915.ko] undefined!
[ 2162s] ERROR: modpost: "__get_random_u32_below" [drivers/scsi/scsi_debug.ko] undefined!
[ 2162s] ERROR: modpost: "__get_random_u32_below" [drivers/net/team/team_mode_random.ko] undefined!
[ 2162s] ERROR: modpost: "__get_random_u32_below" [drivers/media/common/v4l2-tpg/v4l2-tpg.ko] undefined!
[ 2162s] ERROR: modpost: "__get_random_u32_below" [drivers/media/test-drivers/vidtv/dvb-vidtv-demod.ko] undefined!
[ 2162s] ERROR: modpost: "__get_random_u32_below" [drivers/mtd/nand/raw/nandsim.ko] undefined!
[ 2162s] WARNING: modpost: suppressed 17 unresolved symbol warnings because there were too many)
```

**Comment by smuellerDD** [comment]
Am Montag, 26. Dezember 2022, 22:04:17 CET schrieb Oleksandr Natalenko:

Hi Oleksandr,

> Another change that should be accounted for:
> db516da95ce458f0cab5e7ae2db93fd821484d7d ("hw_random: use
> add_hwgenerator_randomness() for early entropy").


This is already considered with patch e9c3511e798c570c16c97be09cd2a57e39f28928

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Montag, 26. Dezember 2022, 21:14:51 CET schrieb Oleksandr Natalenko:

Hi Oleksandr,

> Testing this now:

Patch slightly adopted and applied, thanks.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Montag, 26. Dezember 2022, 22:04:17 CET schrieb Oleksandr Natalenko:

Hi Oleksandr,

> Another change that should be accounted for:
> db516da95ce458f0cab5e7ae2db93fd821484d7d ("hw_random: use
> add_hwgenerator_randomness() for early entropy").

Patch created.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, 27. Dezember 2022, 12:24:08 CET schrieb Oleksandr Natalenko:

Hi Oleksandr,

> It looks like e9a688bcb19348862afe30d7c85bc37c4c293471 ("random: use
> rejection sampling for uniform bounded random integers") must be taken into
> account too, otherwise the following build error occurs:

Patch created.

Ciao
Stephan

**Comment by pfactum** [comment]
The build finishes fine after applying patches, hence closing this issue. Thank you!
