### ISSUE TITLE
build error on linux-6.1.14

### ISSUE THREAD

**Issue by sbwml** [smuellerDD/lrng#28]
I got an error building on linux-6.1.14, here's the information.

```
make[5]: Entering directory '/redhat/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.14'
  CALL    scripts/checksyscalls.sh
  CC      drivers/char/lrng/lrng_es_mgr.o
In file included from drivers/char/lrng/lrng_es_mgr.c:16:
drivers/char/lrng/lrng_drng_atomic.h: In function 'lrng_get_atomic':
drivers/char/lrng/lrng_drng_atomic.h:20:69: error: expected ';' before '}' token
   20 | static inline struct lrng_drng *lrng_get_atomic(void) { return NULL }
      |                                                                     ^
make[9]: *** [scripts/Makefile.build:250: drivers/char/lrng/lrng_es_mgr.o] Error 1
make[8]: *** [scripts/Makefile.build:500: drivers/char/lrng] Error 2
make[7]: *** [scripts/Makefile.build:500: drivers/char] Error 2
make[6]: *** [scripts/Makefile.build:500: drivers] Error 2
make[5]: *** [Makefile:2008: .] Error 2
```

I used: 
https://github.com/smuellerDD/lrng/tree/master/kernel_patches/v6.2 and https://github.com/smuellerDD/lrng/tree/master/backports/v49-6.1.14

**Comment by smuellerDD** [comment]
Am Donnerstag, 2. März 2023, 13:44:31 CET schrieb Bard:

Hi Bard,

> I got an error building on linux-6.1.14, here's the information.
> 
> ```
> make[5]: Entering directory
> '/redhat/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8
> /linux-6.1.14' CALL    scripts/checksyscalls.sh
>   CC      drivers/char/lrng/lrng_es_mgr.o
> In file included from drivers/char/lrng/lrng_es_mgr.c:16:
> drivers/char/lrng/lrng_drng_atomic.h: In function 'lrng_get_atomic':
> drivers/char/lrng/lrng_drng_atomic.h:20:69: error: expected ';' before '}'
> token 20 | static inline struct lrng_drng *lrng_get_atomic(void) { return
> NULL }
>       |                                                                    


Please check the lastest push.

Thanks for the report.

 ^
> 
> make[9]: *** [scripts/Makefile.build:250: drivers/char/lrng/lrng_es_mgr.o]
> Error 1 make[8]: *** [scripts/Makefile.build:500: drivers/char/lrng] Error
> 2 make[7]: *** [scripts/Makefile.build:500: drivers/char] Error 2
> make[6]: *** [scripts/Makefile.build:500: drivers] Error 2
> make[5]: *** [Makefile:2008: .] Error 2
> ```
> 
> I used:
> https://github.com/smuellerDD/lrng/tree/master/kernel_patches/v6.2 and
> https://github.com/smuellerDD/lrng/tree/master/backports/v49-6.1.14
	

Ciao
Stephan

**Comment by sbwml** [comment]
ok i try now

**Comment by sbwml** [comment]
Everything is OK. 👍👍👍
