### ISSUE TITLE
LRNG compatibility with OCF?

### ISSUE THREAD

**Issue by jancheta** [smuellerDD/lrng#29]
Hello! I am working on incorporating LRNG into openWRT with kernel version 4.4.60 and running into build errors related to `crypto/ocf/ocf.ko`. I was able to successfully patch the kernel we are using and am able to get a build working by disabling `CONFIG_PACKAGE_kmod-crypto-ocf` but I wondered if any work has been done in LRNG to work with OCF? We are making use of a cryptographic hardware accelerator + openssl so disabling it is not an ideal pathway for us (though I am in the process of trying to quantify the performance difference). It looks like there is a problem with two functions that are no longer built in as a result of using LRNG. Are there replacement functions I can patch OCF with?

build output example failure
```
...
ERROR: "random_input_wait" [crypto/ocf/ocf.ko] undefined!
ERROR: "random_input_words" [crypto/ocf/ocf.ko] undefined!
...
```

**Comment by smuellerDD** [comment]
Am Donnerstag, 20. April 2023, 02:19:18 CEST schrieb jancheta:

Hi jancheta,

> Hello! I am working on incorporating LRNG into openWRT with kernel version
> 4.4.60

That is quite an old kernel.

> and running into build errors related to `crypto/ocf/ocf.ko`. I was
> able to successfully patch the kernel we are using and am able to get a
> build working by disabling `CONFIG_PACKAGE_kmod-crypto-ocf` but I wondered
> if any work has been done in LRNG to work with OCF? We are making use of a
> cryptographic hardware accelerator + openssl so disabling it is not an
> ideal pathway for us (though I am in the process of trying to quantify the
> performance difference). It looks like there is a problem with two
> functions that are no longer built in as a result of using LRNG. Are there
> replacement functions I can patch OCF with?
> 
> build output example failure
> ```
> ...
> ERROR: "random_input_wait" [crypto/ocf/ocf.ko] undefined!
> ERROR: "random_input_words" [crypto/ocf/ocf.ko] undefined!
> ...
> ```

Hm, I am not aware that there should be any problems. I am compiling the LRNG 
with normal vendor kernels (e.g. SUSE, RHEL, Ubuntu) with all options enabled. 
The kernels I see do not have OCF as you reference. Also searching the 
standard kernels for the call random_input_wait/words I do not find anything. 
So it seems it is an add-on code which seemingly adds these functions.

If you can point me to the kernel code with this OCF support present, I can 
take a look to see how these two functions are implemented. I would hazard to 
guess, they are added to driver/char/random.c - but this file is not compiled 
when the LRNG is enabled. So, these functions would need to be duplicated into 
drivers/char/lrng/lrng_interface_aux.c.

Ciao
Stephan

**Comment by jancheta** [comment]
Hi Stephan!

> That is quite an old kernel.

Unfortunately yes. Often, in my experience, kernel upgrades in embedded devices are not prioritized.

> I would hazard to guess, they are added to driver/char/random.c - but this file is not compiled when the LRNG is enabled.

Yes they are present in my codebase. I am asking around if anyone has the backstory on how those changes made it in there but not finding anything yet. I will update you once I find something available on the web. In the meantime, I can share the code snippets that are there if you have any input on them.

how the functions were defined in `drivers/char/random.c`
```
/* ...
 * add_device_randomness() is for adding data to the random pool that
 * is likely to differ between two devices (or possibly even per boot).
 * This would be things like MAC addresses or serial numbers, or the
 * read-out of the RTC. This does *not* add any actual entropy to the
 * pool, but it initializes the pool to different values for devices
 * that might otherwise be identical and have very little entropy
 * available to them (particularly common in the embedded world).
 *
 *      void random_input_words(__u32 *buf, size_t wordcount, int ent_count)
 *      int random_input_wait(void);
 *
...
 *
 * random_input_words() just provides a raw block of entropy to the input
 * pool, such as from a hardware entropy generator.
 *
 * random_input_wait() suspends the caller until such time as the
 * entropy pool falls below the write threshold, and returns a count of how
 * much entropy (in bits) is needed to sustain the pool.
 *
...
*/
// ...
/*
 * random_input_words - add bulk entropy to pool
 *
 * @buf: buffer to add
 * @wordcount: number of __u32 words to add
 * @ent_count: total amount of entropy (in bits) to credit
 *
 * this provides bulk input of entropy to the input pool
 *
 */
void random_input_words(__u32 *buf, size_t wordcount, int ent_count)
{
	mix_pool_bytes(&input_pool, buf, wordcount*4);

	credit_entropy_bits(&input_pool, ent_count);

	/*
	 * Wake up waiting processes if we have enough
	 * entropy.
	 */
	if (input_pool.entropy_count >= random_read_wakeup_bits)
		wake_up_interruptible(&random_read_wait);
}
EXPORT_SYMBOL(random_input_words);

/*
 * random_input_wait - wait until random needs entropy
 *
 * this function sleeps until the /dev/random subsystem actually
 * needs more entropy, and then return the amount of entropy
 * that it would be nice to have added to the system.
 */
int random_input_wait(void)
{
	int count;

	wait_event_interruptible(random_write_wait, 
			 input_pool.entropy_count < random_write_wakeup_bits);

	count = random_write_wakeup_bits - input_pool.entropy_count;

        /* likely we got woken up due to a signal */
	if (count <= 0) count = random_read_wakeup_bits; 

	pr_notice("requesting %d bits from input_wait()er %d<%d\n",
		  count,
		  input_pool.entropy_count, random_write_wakeup_bits);

	return count;
}
EXPORT_SYMBOL(random_input_wait);
```

Where they are called in `crypto/ocf/random.c`
```
/*
 * while we can add entropy to random.c continue to read random data from
 * the drivers and push it to random.
 */
static int
random_proc(void *arg)
{
	int n;
	int wantcnt;
	int bufcnt = 0;
	int retval = 0;
	int *buf = NULL;

#if LINUX_VERSION_CODE < KERNEL_VERSION(2,6,0)
	daemonize();
	spin_lock_irq(&current->sigmask_lock);
	sigemptyset(&current->blocked);
	recalc_sigpending(current);
	spin_unlock_irq(&current->sigmask_lock);
	scnprintf(current->comm, sizeof(current->comm), "ocf-random");
#elif LINUX_VERSION_CODE >= KERNEL_VERSION(3,8,0)
	recalc_sigpending();
	scnprintf(current->comm, sizeof(current->comm), "ocf-random");
#else
	daemonize("ocf-random");
#endif

	(void) get_fs();
	set_fs(get_ds());

#ifdef CONFIG_OCF_FIPS
#define NUM_INT (RNDTEST_NBYTES/sizeof(int))
#else
#define NUM_INT 32
#endif

	/*
	 * some devices can transferr their RNG data direct into memory,
	 * so make sure it is device friendly
	 */
	buf = kmalloc(NUM_INT * sizeof(int), GFP_DMA);
	if (NULL == buf) {
		printk("crypto: RNG could not allocate memory\n");
		retval = -ENOMEM;
		goto bad_alloc;
	}

	wantcnt = NUM_INT;   /* start by adding some entropy */

	/*
	 * its possible due to errors or driver removal that we no longer
	 * have anything to do,  if so exit or we will consume all the CPU
	 * doing nothing
	 */
	while (!list_empty(&random_ops)) {
		struct random_op	*rops, *tmp;

#ifdef CONFIG_OCF_FIPS
		if (wantcnt)
			wantcnt = NUM_INT; /* FIPs mode can do 20000 bits or none */
#endif

		/* see if we can get enough entropy to make the world
		 * a better place.
		 */
		while (bufcnt < wantcnt && bufcnt < NUM_INT) {
			list_for_each_entry_safe(rops, tmp, &random_ops, random_list) {

				n = (*rops->read_random)(rops->arg, &buf[bufcnt],
							 NUM_INT - bufcnt);

				/* on failure remove the random number generator */
				if (n == -1) {
					list_del(&rops->random_list);
					printk("crypto: RNG (driverid=0x%x) failed, disabling\n",
							rops->driverid);
					kfree(rops);
				} else if (n > 0)
					bufcnt += n;
			}
			/* give up CPU for a bit, just in case as this is a loop */
			schedule();
		}


#ifdef CONFIG_OCF_FIPS
		if (bufcnt > 0 && rndtest_buf((unsigned char *) &buf[0])) {
			dprintk("crypto: buffer had fips errors, discarding\n");
			bufcnt = 0;
		}
#endif

		/*
		 * if we have a certified buffer,  we can send some data
		 * to /dev/random and move along
		 */
		if (bufcnt > 0) {
			/* add what we have */
			random_input_words(buf, bufcnt, bufcnt*sizeof(int)*8);
			bufcnt = 0;
		}

		/* give up CPU for a bit so we don't hog while filling */
		schedule();

		/* wait for needing more */
		wantcnt = random_input_wait();

		if (wantcnt <= 0)
			wantcnt = 0; /* try to get some info again */
		else
		 	/* round up to one word or we can loop forever */
			wantcnt = (wantcnt + (sizeof(int)*8)) / (sizeof(int)*8);
		if (wantcnt > NUM_INT) {
			wantcnt = NUM_INT;
		}

		if (signal_pending(current)) {
#if LINUX_VERSION_CODE < KERNEL_VERSION(2,6,0)
			spin_lock_irq(&current->sigmask_lock);
#endif
			flush_signals(current);
#if LINUX_VERSION_CODE < KERNEL_VERSION(2,6,0)
			spin_unlock_irq(&current->sigmask_lock);
#endif
		}
	}

	kfree(buf);

bad_alloc:
	spin_lock_irq(&random_lock);
	started = 0;
	spin_unlock_irq(&random_lock);

	return retval;
}
```

I understand this may not be enough for you to give an informed response but I will update this thread again if I find the kernel source somewhere or the specific patch file we used.

Thanks!
Justin

**Comment by jancheta** [comment]
and was just linked to where the repo is now hosted

https://git.codelinaro.org/clo/qsdk/oss/kernel/linux-msm/-/tree/4466f30e321dbaf1bc66e900a8f50388e00b20b9

**Comment by smuellerDD** [comment]
Am Donnerstag, 20. April 2023, 22:56:08 CEST schrieb jancheta:

Hi jancheta,

The attached patch should provide the needed interfaces. The patch, however, 
is not even compile-tested.

Ciao
Stephan

**Comment by jancheta** [comment]
Hi Stephan, I am not able to find the patched you mentioned?

-Justin

**Comment by smuellerDD** [comment]
[OCF-support.diff.gz](https://github.com/smuellerDD/lrng/files/11298579/OCF-support.diff.gz)

**Comment by jancheta** [comment]
Hi Stephan,

Really appreciate your quick responses and all the support you have freely given. Unfortunately, since I am on kernel 4.4, I applied your release v43 since that was the latest I could find for 4.4. 

It looks like I would be able to apply the patch you gave me to `lrng_aux.c` instead of `lrng_interface_aux.c`. Applying it to `lrng_aux.c` instead makes it look like `random_input_words` would compile ok since function `lrng_pool_insert_aux` is available. 

I think I would need an updated `lrng_es[lrng_ext_es_aux]->curr_entropy(0)` call since neither lrng_es nor curr_entropy are defined anywhere. In our use case, we are only using CPU Jitter as an entropy source, so I was wondering if using `lrng_jent_entropylevel(0)` instead would suffice?

Of course, I am coming into this blind without great knowledge, so any expertise you can give me is greatly appreciated!

**Comment by smuellerDD** [comment]
Try this patch 
[lrng_add_OCF.diff.gz](https://github.com/smuellerDD/lrng/files/11326351/lrng_add_OCF.diff.gz)

**Comment by jancheta** [comment]
Thanks so much for your support! This worked for my use case.
