### ISSUE TITLE
Randomly, with lrgn an embedded system hangs while booting

### ISSUE THREAD

**Issue by jetm** [smuellerDD/lrng#3]
Using `lrng` with an ARM embedded system, it hangs less while booting than with Linux kernel `/dev/random`. But, randomly it still hangs while systemd is booting. My assumption is the lack of entropy because if I access to the embedded device through telnet and press the `enter` key several times, the system continues booting. 

The embedded system has no HD. It boots on RAM (`tmpfs`). It has an HW random number generator (`/dev/hwrng`), but `rngd` has issues to use it with _lrng_. On userspace `haveged` is being used, but not sure if with `lrng` is still needed. 

Is there a way to diagnose which could be causing the hang while systemd is booting the system?
```
Linux kernel: v4.19.118
lrng: v4.20 patches
systemd: v4.43
```
`lrng` logs when the boot hangs:
```
kernel: lrng_chacha20: ChaCha20 core initialized
kernel: lrng_chacha20: ChaCha20 core initialized
kernel: lrng_base: primary DRNG initially seeded with 48 bits of entropy
kernel: lrng_drbg: DRBG with aes core allocated
kernel: lrng_drbg: Hash cmac(aes) allocated
kernel: lrng_base: primary DRNG and entropy pool read-hash allocated
kernel: lrng_drbg: DRBG with aes core allocated
kernel: lrng_base: secondary DRNG of NUMA node 0 switched
kernel: lrng_base: disallow setting new cipher callbacks, unload the old callbacks first!
kernel: lrng_base: systemd - use of insufficiently seeded DRNG (16 bytes read)
kernel: lrng_base: systemd - use of insufficiently seeded DRNG (16 bytes read)
kernel: lrng_base: systemd - use of insufficiently seeded DRNG (16 bytes read)
kernel: lrng_base: systemd - use of insufficiently seeded DRNG (16 bytes read)
kernel: lrng_base: systemd - use of insufficiently seeded DRNG (16 bytes read)
kernel: lrng_base: systemd - use of insufficiently seeded DRNG (16 bytes read)
kernel: lrng_base: systemd - use of insufficiently seeded DRNG (16 bytes read)
kernel: lrng_base: systemd - use of insufficiently seeded DRNG (16 bytes read)
kernel: lrng_base: systemd - use of insufficiently seeded DRNG (16 bytes read)
kernel: lrng_base: primary DRNG minimally seeded with 144 bits of entropy
kernel: lrng_base: primary DRNG fully seeded with 256 bits of entropy
```

I can provide more logs

**Comment by smuellerDD** [comment]
Am Samstag, 11. Juli 2020, 01:02:28 CEST schrieb Javier Tiá:

Hi Javier,

> Using `lrng` with an ARM embedded system, it hangs less while booting than
> with Linux kernel `/dev/random`. But, randomly it still hangs while systemd
> is booting. My assumption is the lack of entropy because if I access to the
> embedded device through telnet and press the `enter` key several times, the
> system continues booting.
> 
> The embedded system has no HD. It boots on RAM (`tmpfs`). It has an HW
> random number generator (`/dev/hwrng`), but `rngd` has issues to use it
> with _lrng_. On userspace `haveged` is being used, but not sure if with
> `lrng` is still needed.

Thanks a lot for the report.
> 
> Is there a way to diagnose which could be causing the hang while systemd is
> booting the system? ```
> Linux kernel: v4.19.118
> lrng: v4.20 patches
> systemd: v4.43
> ```
> `lrng` logs when the boot hangs:
> ```
> kernel: lrng_chacha20: ChaCha20 core initialized
> kernel: lrng_chacha20: ChaCha20 core initialized
> kernel: lrng_base: primary DRNG initially seeded with 48 bits of entropy
> kernel: lrng_drbg: DRBG with aes core allocated
> kernel: lrng_drbg: Hash cmac(aes) allocated
> kernel: lrng_base: primary DRNG and entropy pool read-hash allocated
> kernel: lrng_drbg: DRBG with aes core allocated
> kernel: lrng_base: secondary DRNG of NUMA node 0 switched
> kernel: lrng_base: disallow setting new cipher callbacks, unload the old
> callbacks first!

This log entry seems to indicate you marked CRYPTO_LRNG_DRBG and 
CRYPTO_LRNG_KCAPI as y. I recommend you only mark one of them with y because 
the LRNG can only consume one DRNG. If you do not select one at all, the 
default ChaCha20 DRNG is used.

> kernel: lrng_base: systemd - use of insufficiently seeded
> DRNG (16 bytes read) kernel: lrng_base: systemd - use of insufficiently
> seeded DRNG (16 bytes read) kernel: lrng_base: systemd - use of
> insufficiently seeded DRNG (16 bytes read) kernel: lrng_base: systemd - use
> of insufficiently seeded DRNG (16 bytes read) kernel: lrng_base: systemd -
> use of insufficiently seeded DRNG (16 bytes read) kernel: lrng_base:
> systemd - use of insufficiently seeded DRNG (16 bytes read) kernel:
> lrng_base: systemd - use of insufficiently seeded DRNG (16 bytes read)
> kernel: lrng_base: systemd - use of insufficiently seeded DRNG (16 bytes
> read) kernel: lrng_base: systemd - use of insufficiently seeded DRNG (16
> bytes read) kernel: lrng_base: primary DRNG minimally seeded with 144 bits
> of entropy kernel: lrng_base: primary DRNG fully seeded with 256 bits of
> entropy ```
> 
> I can provide more logs

The LRNG seems to work as intended. What you can do to increase the 
performance assuming you trust the Jitter RNG is to add the following kernel 
command line argument:

lrng_jent.jitterrng=256

A lower value is also possible.

See [1] section 2.4.3 for details.

See [2] for the entropy assessment of the Jitter RNG.

[1] https://www.chronox.de/lrng/doc/lrng.pdf

[2] https://chronox.de/jent/doc/CPU-Jitter-NPTRNG.pdf


Ciao
Stephan

**Comment by jetm** [comment]
You were right. I was using both _CRYPTO_LRNG_DRBG_ and _CRYPTO_LRNG_KCAPI_. Marked only _CRYPTO_LRNG_DRBG_ with _y_.

Tried `lrng_jent.jitterrng=256`, and no positive result, still boot hangs. Checked that `lrng` parameters in the kernel, and it seems `lrng_jent.jitterrng=256` is not enabled. Just these:
```
ls -R /sys/module/lrng_*
/sys/module/lrng_base:
parameters  uevent

/sys/module/lrng_base/parameters:
archrandom  jitterrng

/sys/module/lrng_drbg:
parameters  uevent

/sys/module/lrng_drbg/parameters:
lrng_drbg_type
```

Would `lrng_base.jitterrng=256` be equivalent to `lrng_jent.jitterrng=256`?

Do I need to integrate `lrng_jent.c` file from `lrng` v5.x patches to the v4.20 patches?

**Comment by smuellerDD** [comment]
Am Montag, 13. Juli 2020, 18:12:51 CEST schrieb Javier Tiá:

Hi Javier,

> You were right. I was using both _CRYPTO_LRNG_DRBG_ and _CRYPTO_LRNG_KCAPI_.
> Marked only _CRYPTO_LRNG_DRBG_ with _y_.
> 
> Tried `lrng_jent.jitterrng=256`, and no positive result, still boot hangs.
> Checked that `lrng` parameters in the kernel, and it seems
> `lrng_jent.jitterrng=256` is not enabled. Just these: ```
> ls -R /sys/module/lrng_*
> /sys/module/lrng_base:
> parameters  uevent
> 
> /sys/module/lrng_base/parameters:
> archrandom  jitterrng
> 
> /sys/module/lrng_drbg:
> parameters  uevent
> 
> /sys/module/lrng_drbg/parameters:
> lrng_drbg_type
> ```
> 
> Would `lrng_base.jitterrng=256` be equivalent to `lrng_jent.jitterrng=256`?

Absolutely - starting with teh 5.6 patches I broke the monolithic lrng_base.c 
file apart into different individual files. This had an impact on the kernel 
command line parameter.

There is no technical difference between both strings apart from the name.
> 
> Do I need to integrate `lrng_jent.c` file from `lrng` v5.x patches to the
> v4.20 patches?

No.

Ciao
Stephan

**Comment by jetm** [comment]
Thanks, Stephan for the clarification.

Tried `lrng_base.jitterrng=256` with different configuration combinations: `LRNG`, `LRNG` + `CRYPTO_LRNG_DRBG`, and `LRNG` + `CRYPTO_LRNG_KCAPI`. Still getting hang.

Thinking of what else to try...

If I change the size of [LRNG_POOL_SIZE](https://github.com/smuellerDD/lrng/blob/master/kernel_patches/v4.20/v20-0002-Linux-Random-Number-Generator.patch#L242) from `128` to `512` to get a pool size of `16384`. Will be enough to increase the pool size by only changing that line with `512`?

**Comment by smuellerDD** [comment]
Am Montag, 13. Juli 2020, 21:53:40 CEST schrieb Javier Tiá:

Hi Javier,

> Thanks, Stephan for the clarification.
> 
> Tried `lrng_base.jitterrng=256` with different configuration combinations:
> `LRNG`, `LRNG` + `CRYPTO_LRNG_DRBG`, and `LRNG` + `CRYPTO_LRNG_KCAPI`.

The output RNGs are not related to the noise sources. Thus, the configuration 
of with or without KCAPI and DRBG is irrelevant here.

> Still getting hang.

The Jitter RNG should do the trick unless you have a coarse timer.

To get a full picture, I would do the following:

1. check that the debugfs file jitterrng indeed contains 256 - if not, the 
kernel command line parameter seems wrong.

2. Enable full debug logging to see what is going on. See the following in the 
cover letter:

"""
Booting the patch with the kernel command line option
"dyndbg=file drivers/char/lrng* +p" generates logs indicating the operation
of the LRNG. Each log is pre-pended with "lrng:".
"""

With that, you should get output similar to the following (this log is from 
the current code base, so yours may slightly differ, but its meaning is the 
same):

[   44.279886] lrng_drng: reseed triggered by interrupt noise source for DRNG 
on
 NUMA node 0
[   44.279891] lrng_pool: obtained 32 bits of entropy from 33 newly collected 
interrupts - not using 0 interrupts
[   44.279893] lrng_archrandom: obtained 8 bits of entropy from CPU RNG noise 
source
[   44.286120] lrng_jent: Jitter RNG working on current system
[   44.287118] lrng_jent: obtained 16 bits of entropy from Jitter RNG noise 
source
[   44.288475] lrng_pool: LRNG initial entropy level 56 bits of entropy
[   44.289053] lrng_drng: seeding regular DRNG with 100 bytes
[   44.289057] lrng_drng: regular DRNG stats since last seeding: 44 secs; 
generate calls: 0

The key is the output from the Jitter RNG: first, it must be considered usable 
and that it is assumed to provide 256 bits of entropy.

> 
> Thinking of what else to try...
> 
> If I change the size of
> [LRNG_POOL_SIZE](https://github.com/smuellerDD/lrng/blob/master/kernel_patc
> hes/v4.20/v20-0002-Linux-Random-Number-Generator.patch#L242) from `128` to
> `512` to get a pool size of `16384`. Will be enough to increase the pool
> size by only changing that line with `512`?

That will most likely not do it because you seem to be starved of entropy.

Ciao
Stephan

**Comment by jetm** [comment]
`lrng_base.jitterrng=256` is getting changed 
```
# cat /sys/module/lrng_base/parameters/jitterrng
256
```
But I am unable to find any reference to `jitter` or `rng` under `/sys/kernel/debug`:
```
# find /sys/kernel/debug -name '*jitter*'
# find /sys/kernel/debug -name '*rng*'
```
and no reference to `debugfs_` inside of `lrng` v4.20 patches.

These are the `lrng` logs with dynamic debug enabled:
```
# journalctl | grep lrng
Jul 06 17:57:56 kernel: lrng_base: reset secondary DRNG
Jul 06 17:57:56 kernel: lrng_chacha20: ChaCha20 core initialized
Jul 06 17:57:56 kernel: lrng_base: reset secondary DRNG
Jul 06 17:57:56 kernel: lrng_base: reset primary DRNG
Jul 06 17:57:56 kernel: lrng_chacha20: ChaCha20 core initialized
Jul 06 17:57:56 kernel: lrng_base: obtained 0 bits of entropy from 0 newly collected interrupts - not using 0 interrupts
Jul 06 17:57:56 kernel: lrng_base: Jitter RNG working on current system
Jul 06 17:57:56 kernel: lrng_base: obtained 256 bits of entropy from Jitter RNG noise source
Jul 06 17:57:56 kernel: lrng_base: reseed primary DRNG from internal noise sources with 256 bits of entropy
Jul 06 17:57:56 kernel: lrng_base: inject 100 bytes with 256 bits of entropy into primary DRNG
Jul 06 17:57:56 kernel: lrng_base: primary DRNG fully seeded with 256 bits of entropy
Jul 06 17:57:56 kernel: lrng_base: obtained 32 bytes of random data from primary DRNG
Jul 06 17:57:56 kernel: lrng_base: primary DRNG entropy level at 0 bits
Jul 06 17:57:56 kernel: lrng_base: seeding secondary DRNG with 32 bytes
Jul 06 17:57:56 kernel: lrng_base: secondary DRNG stats since last seeding: 0 secs; generate calls: 1
Jul 06 17:57:57 kernel: lrng_base: inject 16 bytes with 0 bits of entropy into primary DRNG
Jul 06 17:57:57 kernel: lrng_base: force reseed of secondary DRNG on node 0
Jul 06 17:57:57 kernel: lrng_base: obtained 0 bits of entropy from 0 newly collected interrupts - not using 335 interrupts
Jul 06 17:57:57 kernel: lrng_base: obtained 256 bits of entropy from Jitter RNG noise source
Jul 06 17:57:57 kernel: lrng_base: reseed primary DRNG from internal noise sources with 256 bits of entropy
Jul 06 17:57:57 kernel: lrng_base: inject 100 bytes with 256 bits of entropy into primary DRNG
Jul 06 17:57:57 kernel: lrng_base: obtained 32 bytes of random data from primary DRNG
Jul 06 17:57:57 kernel: lrng_base: primary DRNG entropy level at 0 bits
Jul 06 17:57:57 kernel: lrng_base: seeding secondary DRNG with 32 bytes
Jul 06 17:57:57 kernel: lrng_base: obtained 0 bits of entropy from 0 newly collected interrupts - not using 340 interrupts
Jul 06 17:57:57 kernel: lrng_base: secondary DRNG stats since last seeding: 15 secs; generate calls: 2907
Jul 06 17:57:57 kernel: lrng_base: obtained 256 bits of entropy from Jitter RNG noise source
Jul 06 17:57:57 kernel: lrng_base: reseed primary DRNG from internal noise sources with 256 bits of entropy
Jul 06 17:57:57 kernel: lrng_base: inject 100 bytes with 256 bits of entropy into primary DRNG
Jul 06 17:57:57 kernel: lrng_base: obtained 32 bytes of random data from primary DRNG
Jul 06 17:57:57 kernel: lrng_base: primary DRNG entropy level at 0 bits
Jul 06 17:57:57 kernel: lrng_base: seeding secondary DRNG with 32 bytes
Jul 06 17:57:57 kernel: lrng_base: secondary DRNG stats since last seeding: 0 secs; generate calls: 780
```

**Comment by smuellerDD** [comment]
Am Dienstag, 14. Juli 2020, 20:43:36 CEST schrieb Javier Tiá:

Hi Javier,

> `lrng_base.jitterrng=256` is getting changed
> ```
> # cat /sys/module/lrng_base/parameters/jitterrng
> 256
> ```
> But I am unable to find any reference to `jitter` or `rng` under
> `/sys/kernel/debug`: ```
> # find /sys/kernel/debug -name '*jitter*'
> # find /sys/kernel/debug -name '*rng*'
> ```

There is none, why would you want to look for it?

> and no reference to `debugfs_` inside of `lrng` v4.20 patches.
> 
> These are the `lrng` logs with dynamic debug enabled:
> ```
> # journalctl | grep lrng
> Jul 06 17:57:56 kernel: lrng_base: reset secondary DRNG
> Jul 06 17:57:56 kernel: lrng_chacha20: ChaCha20 core initialized
> Jul 06 17:57:56 kernel: lrng_base: reset secondary DRNG
> Jul 06 17:57:56 kernel: lrng_base: reset primary DRNG
> Jul 06 17:57:56 kernel: lrng_chacha20: ChaCha20 core initialized
> Jul 06 17:57:56 kernel: lrng_base: obtained 0 bits of entropy from 0 newly
> collected interrupts - not using 0 interrupts
> Jul 06 17:57:56 kernel:
> lrng_base: Jitter RNG working on current system 
> Jul 06 17:57:56 kernel:
> lrng_base: obtained 256 bits of entropy from Jitter RNG noise source

So, the Jitter RNG does provide sufficient entropy.

> Jul 06
> 17:57:56 kernel: lrng_base: reseed primary DRNG from internal noise sources
> with 256 bits of entropy
> Jul 06 17:57:56 kernel: lrng_base: inject 100
> bytes with 256 bits of entropy into primary DRNG
> Jul 06 17:57:56 kernel:
> lrng_base: primary DRNG fully seeded with 256 bits of entropy
> Jul 06
> 17:57:56 kernel: lrng_base: obtained 32 bytes of random data from primary
> DRNG
> Jul 06 17:57:56 kernel: lrng_base: primary DRNG entropy level at 0
> bits
> Jul 06 17:57:56 kernel: lrng_base: seeding secondary DRNG with 32
> bytes

At this point, getrandom(2) unblocks and systemd (who uses it) does not block 
any more.

The question is when this happens in relationship to your boot sequence.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Mittwoch, 15. Juli 2020, 18:32:01 CEST schrieb Javier Tiá:

Hi Javier,

> In the boot sequence after `Jul 06 17:57:56 kernel: lrng_base: seeding
> secondary DRNG with 32 bytes`
 ```
> Jul 06 17:57:57 systemd-udevd[326]: ethtool: autonegotiation is unset or
> enabled, the speed and duplex are not writable.
 Jul 06 17:57:57
> systemd-udevd[318]: ethtool: autonegotiation is unset or enabled, the speed
> and duplex are not writable. Jul 06 17:57:57 systemd-udevd[317]: ethtool:
> autonegotiation is unset or enabled, the speed and duplex are not writable.
> Jul 06 17:57:58 systemd-vconsole-setup[340]: KD_FONT_OP_GET failed while
> trying to get the font metadata: Function not implemented Jul 06 17:57:58
> systemd-vconsole-setup[340]: Fonts will not be copied to remaining consoles
> Jul 06 17:58:28 systemd[1]: Bus private-bus-connection: changing state
> RUNNING → CLOSING Jul 06 17:58:28 systemd[1]: systemd-update-utmp.service:
> Failed to send unit change signal for systemd-update-utmp.service:
> Connection reset by peer Jul 06 17:58:28 systemd[1]:
> systemd-resolved.service: Got notification message from PID 335
> (WATCHDOG=1) Jul 06 17:58:28 systemd[1]: systemd-resolved.service: Got
> notification message from PID 335 (READY=1, STATUS=Processing requests...)
> Jul 06 17:58:28 systemd[1]: systemd-resolved.service: Changed start ->
> running Jul 06 17:58:28 systemd[1]: systemd-resolved.service: Job 62
> systemd-resolved.service/start finished, result=done Jul 06 17:58:28
> systemd[1]: Started Network Name Resolution.
> ```
> It gets stuck on `Jul 06 17:58:28 systemd[1]: Bus private-bus-connection:
> changing state RUNNING → CLOSING`, as it takes around `30s` to pass from
> `RUNNING` to `CLOSING`

Compared to the list about the LRNG seeding, the LRNG is fully seeded before 
this blocking.

And as you do not have the log about having the LRNG insufficiently seeded, I 
would not think the seeding is at fault here.

Did you check systemd-analyze to find out which particular systemd target is 
waiting here?
 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/smuellerDD/lrng/issues/3#issuecomment-658867152


Ciao
Stephan

**Comment by jetm** [comment]
Hi Stephan,

> Compared to the list about the LRNG seeding, the LRNG is fully seeded before this blocking.

Understood.

> And as you do not have the log about having the LRNG insufficiently seeded, I would not think the seeding is at fault here.

If the seeding is not the fault here. Is systemd getting empty the seed pool while is booting?

> Did you check systemd-analyze to find out which particular systemd target is waiting here?

yes, these are the output:
```
# systemd-analyze blame
1min 32.168s systemd-logind.service
30.721s systemd-user-sessions.service
821ms dev-hugepages.mount
785ms dev-mqueue.mount
759ms sys-kernel-debug.mount
730ms tmp.mount
...
# systemd-analyze critical-chain
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

multi-user.target @6min 28.500s
`-getty.target @6min 28.484s
`-serial-getty@ttyS0.service @6min 28.469s
`-systemd-user-sessions.service @5min 15.565s +30.721s
`-basic.target @3min 43.404s
`-sockets.target @3min 12.684s
`-rpcbind.socket @2min 41.964s
`-sysinit.target @39.084s
`-systemd-update-done.service @8.629s +28ms
`-systemd-journal-catalog-update.service @8.501s +57ms
`-systemd-tmpfiles-setup.service @8.432s +33ms
`-local-fs.target @8.396s
`-var-volatile.mount @8.317s +31ms
`-local-fs-pre.target @8.300s
`-systemd-tmpfiles-setup-dev.service @8.270s +15ms
`-systemd-sysusers.service @8.221s +31ms
`-systemd-remount-fs.service @7.804s +364ms
`-systemd-journald.socket @7.057s
`-system.slice @2.952s
`--.slice @2.943s
```
but, in another boot, both commands output were different:
```
4min 5.626s systemd-resolved.service
2min 2.888s systemd-logind.service
1min 1.441s systemd-user-sessions.service
815ms dev-hugepages.mount
777ms dev-mqueue.mount
751ms sys-kernel-debug.mount
722ms tmp.mount
```
```
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

multi-user.target @7min 18.444s
`-getty.target @7min 18.444s
`-serial-getty@ttyS0.service @6min 47.725s
`-systemd-user-sessions.service @3min 43.405s +1min 1.441s
`-basic.target @2min 11.244s
`-sockets.target @1min 40.524s
`-rpcbind.socket @1min 9.804s
`-sysinit.target @8.636s
`-systemd-update-done.service @8.584s +32ms
`-systemd-journal-catalog-update.service @8.482s +48ms
`-systemd-tmpfiles-setup.service @8.401s +47ms
`-local-fs.target @8.368s
`-var-volatile.mount @8.305s +46ms
`-local-fs-pre.target @8.288s
`-systemd-tmpfiles-setup-dev.service @8.258s +15ms
`-systemd-sysusers.service @8.209s +31ms
`-systemd-remount-fs.service @7.796s +357ms
`-systemd-journald.socket @7.049s
`--.mount @2.942s
`-systemd-journald.socket @7.049s
`-...
```
And in more booting is always between `systemd-logind.service`, `systemd-resolved.service`, and `systemd-user-sessions.service`

**Comment by jetm** [comment]
> At this point, getrandom(2) unblocks and systemd (who uses it) does not block any more.

If `systemd` is not blocking anymore, it should be something under. One common component is `dbus`, it seems is using [fd = open ("/dev/urandom", O_RDONLY)](https://gitlab.freedesktop.org/dbus/dbus/-/blob/dbus-1.12/dbus/dbus-sysdeps-unix.c#L3196). On these conditions could be `dbus` getting empty the pool?

**Comment by smuellerDD** [comment]
Am Donnerstag, 16. Juli 2020, 04:58:03 CEST schrieb Javier Tiá:

Hi Javier,

> > At this point, getrandom(2) unblocks and systemd (who uses it) does not
> > block any more.
> If `systemd` is not blocking anymore, it should be something under. One
> common component is `dbus`, it seems is using [fd = open ("/dev/urandom",
> O_RDONLY)](https://gitlab.freedesktop.org/dbus/dbus/-/blob/dbus-1.12/dbus/d
> bus-sysdeps-unix.c#L3196). On these conditions could be `dbus` getting empty
> the pool?

/dev/urandom never blocks. Besides, even getrandom(2) would not block at that 
point because the LRNG got fully seeded.

So, I am not sure this blocking is related to the RNG at this point. Can you 
trace dbus to see what it is waiting on?

Ciao
Stephan

**Comment by jetm** [comment]
Hi Stephan,

> So, I am not sure this blocking is related to the RNG at this point. Can you trace dbus to see what it is waiting on?

Putting `strace` on `dbus` didn't work. The `dbus-daemon` failed to start. I put `strace` on PID 1 for `systemd`, and that worked. With strace on PID 1 extracted the syscalls with more durations, assuming is where the boot was stocked. Found these syscall:
```
1 <... close resumed>) = 0 30.110799
260 <... epoll_pwait resumed>[{EPOLLIN, {u32=4408304, u64=4408304}}], 19, -1, NULL, 8) = 1 27.899032
1 <... close resumed>) = 0 30.094991
260 <... epoll_pwait resumed>[{EPOLLIN, {u32=4408304, u64=4408304}}], 19, -1, NULL, 8) = 1 29.897857
1 <... close resumed>) = 0 9.895139
291 <... epoll_pwait resumed>[{EPOLLIN, {u32=4675984, u64=4675984}}], 14, -1, NULL, 8) = 1 70.298984
277 <... epoll_pwait resumed>[{EPOLLIN, {u32=4988208, u64=4988208}}], 10, -1, NULL, 8) = 1 65.351797
```
last column is the duration on secs. From the process ID, these were the process with more duration
```
# ps -p 260 -o comm=
systemd-journal
# ps -p 291 -o comm=
systemd-resolve
# ps -p 277 -o comm=
systemd-udevd
```
All of them are `epoll_pwait`

**Comment by smuellerDD** [comment]
Am Freitag, 17. Juli 2020, 04:54:37 CEST schrieb Javier Tiá:

Hi Javier,

> Hi Stephan,
> 
> > So, I am not sure this blocking is related to the RNG at this point. Can
> > you trace dbus to see what it is waiting on?
> Putting `strace` on `dbus` didn't work. The `dbus-daemon` failed to start. I
> put `strace` on PID 1 for `systemd`, and that worked. With strace on PID 1
> extracted the syscalls with more durations, assuming is where the boot was
> stocked. Found these syscall: ```
> 1 <... close resumed>) = 0 30.110799
> 260 <... epoll_pwait resumed>[{EPOLLIN, {u32=4408304, u64=4408304}}], 19,
> -1, NULL, 8) = 1 27.899032 1 <... close resumed>) = 0 30.094991
> 260 <... epoll_pwait resumed>[{EPOLLIN, {u32=4408304, u64=4408304}}], 19,
> -1, NULL, 8) = 1 29.897857 1 <... close resumed>) = 0 9.895139
> 291 <... epoll_pwait resumed>[{EPOLLIN, {u32=4675984, u64=4675984}}], 14,
> -1, NULL, 8) = 1 70.298984 277 <... epoll_pwait resumed>[{EPOLLIN,
> {u32=4988208, u64=4988208}}], 10, -1, NULL, 8) = 1 65.351797 ```
> last column is the duration on secs. From the process ID, these were the
> process with more duration ```
> # ps -p 260 -o comm=
> systemd-journal
> # ps -p 291 -o comm=
> systemd-resolve
> # ps -p 277 -o comm=
> systemd-udevd
> ```
> All of them are `epoll_pwait`

This seems to be the IPC between the different systemd processes. Yet, I fail 
to find a circle back to the RNG.

Ciao
Stephan

**Comment by jetm** [comment]
Hi Stephan,

Yes, with all the information above, it is no longer an issue on LRNG.

Thank you so much for all the help and kind responses. I am closing the issue.

**Comment by jetm** [comment]
@smuellerDD I want to let you know the original issue was solved. The serial driver was producing the hang due to many logs.

**Comment by smuellerDD** [comment]
Thank you for reporting the root cause and letting me know that the LRNG works as expected.
