### ISSUE TITLE
getrawentropy gets no output

### ISSUE THREAD

**Issue by jancheta** [smuellerDD/lrng#30]
Hello,

I am trying to run https://github.com/smuellerDD/lrng/blob/v43/test/getrawentropy.c and I get no output when I try running it.

various information:
```
root@X7032223C:~# uname -a
Linux X7032223C 4.4.60 #1 SMP PREEMPT Fri Jun 23 20:25:53 UTC 2023 armv7l GNU/Linux

root@X7032223C:~# zcat /proc/config.gz | grep -i lrng
CONFIG_LRNG=y
# CONFIG_LRNG_OVERSAMPLE_ENTROPY_SOURCES is not set
CONFIG_LRNG_OVERSAMPLE_ES_BITS=0
CONFIG_LRNG_SEED_BUFFER_INIT_ADD_BITS=0
# CONFIG_LRNG_IRQ is not set
CONFIG_LRNG_RCT_CUTOFF=31
CONFIG_LRNG_APT_CUTOFF=325
CONFIG_LRNG_JENT=y
CONFIG_LRNG_JENT_ENTROPY_RATE=256
# CONFIG_LRNG_CPU is not set
CONFIG_LRNG_CPU_FULL_ENT_MULTIPLIER=1
CONFIG_LRNG_DRNG_SWITCH=y
CONFIG_LRNG_KCAPI_HASH=y
CONFIG_LRNG_DRBG=m
CONFIG_LRNG_KCAPI=m
CONFIG_LRNG_TESTING_MENU=y
CONFIG_LRNG_RAW_HIRES_ENTROPY=y
# CONFIG_LRNG_RAW_JIFFIES_ENTROPY is not set
# CONFIG_LRNG_RAW_IRQ_ENTROPY is not set
# CONFIG_LRNG_RAW_IRQFLAGS_ENTROPY is not set
# CONFIG_LRNG_RAW_RETIP_ENTROPY is not set
# CONFIG_LRNG_RAW_REGS_ENTROPY is not set
# CONFIG_LRNG_RAW_ARRAY is not set
# CONFIG_LRNG_IRQ_PERF is not set
CONFIG_LRNG_ACVT_HASH=y
# CONFIG_LRNG_RUNTIME_ES_CONFIG is not set
# CONFIG_LRNG_RUNTIME_MAX_WO_RESEED_CONFIG is not set
# CONFIG_LRNG_TEST_CPU_ES_COMPRESSION is not set
CONFIG_LRNG_TESTING=y
CONFIG_LRNG_SELFTEST=y
# CONFIG_LRNG_SELFTEST_PANIC is not set

root@X7032223C:~# cat /proc/lrng_type
DRNG name: ChaCha20 DRNG
LRNG security strength in bits: 160
number of DRNG instances: 1
Standards compliance:
Entropy Sources: JitterRNG Auxiliary
LRNG minimally seeded: true
LRNG fully seeded: true
Auxiliary ES properties:
 Hash for operating entropy pool: SHA-1
JitterRNG ES properties:
 Enabled: true

root@X7032223C:~# cat /proc/cmdline
console=ttyMSM0,115200n8 lrng_testing.boot_test=1 rootfsname=rootfs_1 gpt rootwait swiotlb=1 pci=nomsi fips=1

root@X7032223C:~# ls -la /lib/modules/4.4.60/ | grep lrng
-rw-r--r--    1 root     root          6278 Jun 23 20:29 lrng_drbg.ko
-rw-r--r--    1 root     root          7338 Jun 23 20:29 lrng_kcapi.ko
``` 

I have tried setting lrng_testing.boot_test to 0 as well. I have also tried loading any combination the lrng kernel modules to see if that would make a difference.

In the end, trying to run `./getrawentropy -s 1000000 | tee lrng_raw_noise.data` never prints anything out on the console or in the file.

Do you see anything that I might be doing wrong or any suggestions on different things I can try?

**Comment by smuellerDD** [comment]
Am Mittwoch, 28. Juni 2023, 01:00:42 CEST schrieb jancheta:

Hi jancheta,

> I have tried setting lrng_testing.boot_test to 0 as well. I have also tried
> loading any combination the lrng kernel modules to see if that would make a
> difference.
> 
> In the end, trying to run `./getrawentropy -s 1000000 | tee
> lrng_raw_noise.data` never prints anything out on the console or in the
> file.
> 
> Do you see anything that I might be doing wrong or any suggestions on
> different things I can try?


The data comes in chunks of 1000*sizeof(uint32_t). The command you are using 
requests the raw data for the interrupt entropy source. That means, you need 
at least 1024 interrupts before the command returns something, let alone 1 mil 
interrupts.

So, either you wait for a long time to get all requested data on a regularly 
loaded system, or you cause interrupts. This can easily be triggered, for 
example, by ping flooding (ping -f) the test system from a remote system.

For boot time tests (i.e. boot_test is set to 1), invoke the getrawentropy 
without the -s value as only 1000 values are gathered.

Use the getrawentropy -f option to access other test interface files to obtain 
data from other entropy sources.

Ciao
Stephan

**Comment by jancheta** [comment]
Thanks for that information Stephan. I think I may be trying to test the wrong thing then. I am working on getting FIPS validation on our device and we only enabled the jitter entropy source. Would testing the default test interface (`/sys/kernel/debug/lrng_testing/lrng_raw_hires`) exercise the jitter software entropy? Is this similar to the jitterentropy-library testing (https://github.com/smuellerDD/jitterentropy-library/tree/master/tests/raw-entropy/recording_runtime_kernelspace)? I just wonder if I have my kernel config wrong somewhere?

Unfortunately, even if I do `ping -f` nothing is happening. 

Sorry for my ignorance, I am trying to figure this all out.

**Comment by smuellerDD** [comment]
Am Mittwoch, 28. Juni 2023, 23:57:20 CEST schrieb jancheta:

Hi jancheta,

> Thanks for that information Stephan. I think I may be trying to test the
> wrong thing then. I am working on getting FIPS validation on our device and
> we only enabled the jitter entropy source. Would testing the default test
> interface (`/sys/kernel/debug/lrng_testing/lrng_raw_hires`) exercise the
> jitter software entropy?

No.

The Jitter RNG is a completely standalone entropy source that has its own test 
infrastructure. I assume you use a kernel with the LFSR conditioning 
operation.

This is tested with the code in https://github.com/smuellerDD/jitterentropy-library/tree/master/tests/raw-entropy/recording_runtime_kernelspace/attic 
considering that it is now old code. Yes, I understand the code locations 
could be a bit more structured. But that requires time :-)

Check the README there.

Only if you use the current upstream code with the SHA-3 support, then 
https://github.com/smuellerDD/jitterentropy-library/tree/master/tests/raw-entropy/recording_runtime_kernelspace is to be used.

> Is this similar to the jitterentropy-library
> testing
> (https://github.com/smuellerDD/jitterentropy-library/tree/master/tests/raw-> entropy/recording_runtime_kernelspace)? I just wonder if I have my kernel
> config wrong somewhere?
> 
> Unfortunately, even if I do `ping -f` nothing is happening.

Sure, if you have disabled the IRQ entropy source, then nothing is happening 
there, too.

The make menuconfig documents the following interfaces, there you do not find 
any Jitter RNG related ones.

config LRNG_RAW_HIRES_ENTROPY
        bool "Interface to obtain raw unprocessed IRQ noise source data"
        default y
        depends on LRNG_IRQ
        select LRNG_TESTING
        select LRNG_TESTING_RECORDING
        help
          The test interface allows a privileged process to capture
          the raw unconditioned high resolution time stamp noise that
          is collected by the LRNG for statistical analysis. Extracted
          noise data is not used to seed the LRNG.

          The raw noise data can be obtained using the lrng_raw_hires
          debugfs file. Using the option lrng_testing.boot_raw_hires_test=1
          the raw noise of the first 1000 entropy events since boot
          can be sampled.

config LRNG_RAW_JIFFIES_ENTROPY
        bool "Entropy test interface to Jiffies of IRQ noise source"
        depends on LRNG_IRQ
        select LRNG_TESTING
        select LRNG_TESTING_RECORDING
        help
          The test interface allows a privileged process to capture
          the raw unconditioned Jiffies that is collected by
          the LRNG for statistical analysis. This data is used for
          seeding the LRNG if a high-resolution time stamp is not
          available. If a high-resolution time stamp is detected,
          the Jiffies value is not collected by the LRNG and no
          data is provided via the test interface. Extracted noise
          data is not used to seed the random number generator.

          The raw noise data can be obtained using the lrng_raw_jiffies
          debugfs file. Using the option lrng_testing.boot_raw_jiffies_test=1
          the raw noise of the first 1000 entropy events since boot
          can be sampled.

config LRNG_RAW_IRQ_ENTROPY
        bool "Entropy test interface to IRQ number noise source"
        depends on LRNG_IRQ
        select LRNG_TESTING
        select LRNG_TESTING_RECORDING
        help
          The test interface allows a privileged process to capture
          the raw unconditioned interrupt number that is collected by
          the LRNG for statistical analysis. Extracted noise data is
          not used to seed the random number generator.

          The raw noise data can be obtained using the lrng_raw_irq
          debugfs file. Using the option lrng_testing.boot_raw_irq_test=1
          the raw noise of the first 1000 entropy events since boot
          can be sampled.

config LRNG_RAW_RETIP_ENTROPY
        bool "Entropy test interface to RETIP value of IRQ noise source"
        depends on LRNG_IRQ
        select LRNG_TESTING
        select LRNG_TESTING_RECORDING
        help
          The test interface allows a privileged process to capture
          the raw unconditioned return instruction pointer value
          that is collected by the LRNG for statistical analysis.
          Extracted noise data is not used to seed the random number
          generator.

          The raw noise data can be obtained using the lrng_raw_retip
          debugfs file. Using the option lrng_testing.boot_raw_retip_test=1
          the raw noise of the first 1000 entropy events since boot
          can be sampled.

config LRNG_RAW_REGS_ENTROPY
        bool "Entropy test interface to IRQ register value noise source"
        depends on LRNG_IRQ
        select LRNG_TESTING
        select LRNG_TESTING_RECORDING
        help
          The test interface allows a privileged process to capture
          the raw unconditioned interrupt register value that is
          collected by the LRNG for statistical analysis. Extracted noise
          data is not used to seed the random number generator.

          The raw noise data can be obtained using the lrng_raw_regs
          debugfs file. Using the option lrng_testing.boot_raw_regs_test=1
          the raw noise of the first 1000 entropy events since boot
          can be sampled.

config LRNG_RAW_ARRAY
        bool "Test interface to LRNG raw entropy IRQ storage array"
        depends on LRNG_IRQ
        select LRNG_TESTING
        select LRNG_TESTING_RECORDING
        help
          The test interface allows a privileged process to capture
          the raw noise data that is collected by the LRNG
          in the per-CPU array for statistical analysis. The purpose
          of this interface is to verify that the array handling code
          truly only concatenates data and provides the same entropy
          rate as the raw unconditioned noise source when assessing
          the collected data byte-wise.

          The data can be obtained using the lrng_raw_array debugfs
          file. Using the option lrng_testing.boot_raw_array=1
          the raw noise of the first 1000 entropy events since boot
          can be sampled.

config LRNG_IRQ_PERF
        bool "LRNG interrupt entropy source performance monitor"
        depends on LRNG_IRQ
        select LRNG_TESTING
        select LRNG_TESTING_RECORDING
        help
          With this option, the performance monitor of the LRNG
          interrupt handling code is enabled. The file provides
          the execution time of the interrupt handler in
          cycles.

          The interrupt performance data can be obtained using
          the lrng_irq_perf debugfs file. Using the option
          lrng_testing.boot_irq_perf=1 the performance data of
          the first 1000 entropy events since boot can be sampled.

comment "Scheduler Entropy Source Test Interfaces"

config LRNG_RAW_SCHED_HIRES_ENTROPY
        bool "Interface to obtain raw unprocessed scheduler noise source data"
        depends on LRNG_SCHED
        select LRNG_TESTING
        select LRNG_TESTING_RECORDING
        help
          The test interface allows a privileged process to capture
          the raw unconditioned high resolution time stamp noise that
          is collected by the LRNG for the Scheduler-based noise source
          for statistical analysis. Extracted  noise data is not used to
          seed the LRNG.

          The raw noise data can be obtained using the lrng_raw_sched_hires
          debugfs file. Using the option
          lrng_testing.boot_raw_sched_hires_test=1 the raw noise of the
          first 1000 entropy events since boot can be sampled.


config LRNG_RAW_SCHED_PID_ENTROPY
        bool "Entropy test interface to PID value"
        depends on LRNG_SCHED
        select LRNG_TESTING
        select LRNG_TESTING_RECORDING
        help
          The test interface allows a privileged process to capture
          the raw unconditioned PID value that is collected by the
          LRNG for statistical analysis. Extracted noise
          data is not used to seed the random number generator.

          The raw noise data can be obtained using the
          lrng_raw_sched_pid debugfs file. Using the option
          lrng_testing.boot_raw_sched_pid_test=1
          the raw noise of the first 1000 entropy events since boot
          can be sampled.

config LRNG_RAW_SCHED_START_TIME_ENTROPY
        bool "Entropy test interface to task start time value"
        depends on LRNG_SCHED
        select LRNG_TESTING
        select LRNG_TESTING_RECORDING
        help
          The test interface allows a privileged process to capture
          the raw unconditioned task start time value that is collected
          by the LRNG for statistical analysis. Extracted noise
          data is not used to seed the random number generator.

          The raw noise data can be obtained using the
          lrng_raw_sched_starttime debugfs file. Using the option
          lrng_testing.boot_raw_sched_starttime_test=1
          the raw noise of the first 1000 entropy events since boot
          can be sampled.


config LRNG_RAW_SCHED_NVCSW_ENTROPY
        bool "Entropy test interface to task context switch numbers"
        depends on LRNG_SCHED
        select LRNG_TESTING
        select LRNG_TESTING_RECORDING
        help
          The test interface allows a privileged process to capture
          the raw unconditioned task numbers of context switches that
          are collected by the LRNG for statistical analysis. Extracted
          noise data is not used to seed the random number generator.

          The raw noise data can be obtained using the
          lrng_raw_sched_nvcsw debugfs file. Using the option
          lrng_testing.boot_raw_sched_nvcsw_test=1
          the raw noise of the first 1000 entropy events since boot
          can be sampled.

config LRNG_SCHED_PERF
        bool "LRNG scheduler entropy source performance monitor"
        depends on LRNG_SCHED
        select LRNG_TESTING
        select LRNG_TESTING_RECORDING
        help
          With this option, the performance monitor of the LRNG
          scheduler event handling code is enabled. The file provides
          the execution time of the interrupt handler in cycles.

          The scheduler performance data can be obtained using
          the lrng_sched_perf debugfs file. Using the option
          lrng_testing.boot_sched_perf=1 the performance data of
          the first 1000 entropy events since boot can be sampled.

comment "Auxiliary Test Interfaces"

config LRNG_ACVT_HASH
        bool "Enable LRNG ACVT Hash interface"
        select LRNG_TESTING
        help
          With this option, the LRNG built-in hash function used for
          auxiliary pool management and prior to switching the
          cryptographic backends is made available for ACVT. The
          interface allows writing of the data to be hashed
          into the interface. The read operation triggers the hash
          operation to generate message digest.

          The ACVT interface is available with the lrng_acvt_hash
          debugfs file.

config LRNG_RUNTIME_MAX_WO_RESEED_CONFIG
        bool "Enable runtime configuration of max reseed threshold"
        help
          When enabling this option, the LRNG provides an interface
          allowing the setting of the maximum number of DRNG generate
          operations without a reseed that has full entropy. The
          interface is lrng_drng.max_wo_reseed.

config LRNG_RUNTIME_FORCE_SEEDING_DISABLE
        bool "Enable runtime configuration of force seeding"
        help
          When enabling this option, the LRNG provides an interface
          allowing the disabling of the force seeding when the DRNG
          is not fully seeded but entropy is available.

config LRNG_TEST_CPU_ES_COMPRESSION
        bool "Force CPU ES compression operation"
        help
          When enabling this option, the CPU ES compression operation
          is forced by setting an arbitrary value > 1 for the data
          multiplier even when the CPU ES would deliver full entropy.
          This allows testing of the compression operation. It
          therefore forces to pull more data from the CPU ES
          than what may be required.

endif #LRNG_TESTING_MENU

> 
> Sorry for my ignorance, I am trying to figure this all out.


Ciao
Stephan

**Comment by jancheta** [comment]
Thanks for the information Stephan. Since we are on an older kernel (4.4.60) and using v43 of LRNG, can you point me to the correct version of the jitter entropy test? I assume the master branch would be much too new for my use case. Is there a specific version (tag) I can use?

**Comment by smuellerDD** [comment]
Am Donnerstag, 29. Juni 2023, 18:47:48 CEST schrieb jancheta:

Hi jancheta,

> Thanks for the information Stephan. Since we are on an older kernel (4.4.60)
> and using v43 of LRNG, can you point me to the correct version of the
> jitter entropy test?

The one in the attic directory would do.

> I assume the master branch would be much too new for
> my use case. Is there a specific version (tag) I can use?

The attic in the master branch contains the old code.


Ciao
Stephan

**Comment by jancheta** [comment]
thanks so much for your help Stephan! I am getting output now with the jitterentropy testing and will be going through the validation.

**Comment by jancheta** [comment]
Hi Stephan,

I did have one more question about running the restart jitter entropy testing (found here: https://github.com/smuellerDD/jitterentropy-library/tree/master/tests/raw-entropy/recording_restart_kernelspace).

It script references patch `0001-crypto-jitter-add-interface-for-gathering-of-raw-ent.patch` and (I assume) the associated kernel config option `CONFIG_CRYPTO_USER_API_RNG`. I cannot seem to locate that patch anywhere and hoped you could point me in the right direction?

The script also relies on the libkcapi helper tool `kcapi-rng`. I was also wondering if there were instructions on any of your repos on how to build that tool. Or is that tool already normally available? I had not checked before and just realized my kernel actually does contain that option. There is no other patch file associated/needed?

```
// in linux-4.4/crypto/Kconfig
...
config CRYPTO_USER_API_RNG
	tristate "User-space interface for random number generator algorithms"
	depends on NET
	select CRYPTO_RNG
	select CRYPTO_USER_API
	help
	  This option enables the user-spaces interface for random
	  number generator algorithms.
...
```

These changes should then make getrawentropy actually return something since the the other test interface would be available and I could use it with the `-f` command line option of getrawentropy?

Sorry again if this is not the right location for all these questions. But (I think) I should be able to make my way forward after this since all that would be left for me to do was adapt the code for init.d instead of systemd.

Thank you so much for your time!

**Comment by jancheta** [comment]
Hi Stephan,

I have been able to build libkcapi and kcapi-rng with help from https://github.com/egorenar/openwrt-packages-custom/tree/master/libkcapi.

I think all that is left is to figure out the `0001-crypto-jitter-add-interface-for-gathering-of-raw-ent.patch` so that getrawentropy can read from the jent_raw_hires debug file? Or should I be using the jitterentropy-foldtime like for the runtime tests?

**Comment by smuellerDD** [comment]
Am Freitag, 7. Juli 2023, 01:31:03 CEST schrieb jancheta:

Hi jancheta,

> Hi Stephan,
> 
> I did have one more question about running the restart jitter entropy
> testing (found here:
> https://github.com/smuellerDD/jitterentropy-library/tree/master/tests/raw-e
> ntropy/recording_restart_kernelspace).

This is only applicable for the latest Jitter RNG marked as 3.4.0 in 6.5-rc*.
> 
> It script references patch
> `0001-crypto-jitter-add-interface-for-gathering-of-raw-ent.patch` and (I
> assume) the associated kernel config option `CONFIG_CRYPTO_USER_API_RNG`. I
> cannot seem to locate that patch anywhere and hoped you could point me in
> the right direction?

See above.
> 
> The script also relies on the libkcapi helper tool `kcapi-rng`. I was also
> wondering if there were instructions on any of your repos on how to build
> that tool. Or is that tool already normally available? I had not checked
> before and just realized my kernel actually does contain that option. There
> is no other patch file associated/needed?

See libkcapi.
> 
> ```
> // in linux-4.4/crypto/Kconfig
> ...
> config CRYPTO_USER_API_RNG
> 	tristate "User-space interface for random number generator algorithms"
> 	depends on NET
> 	select CRYPTO_RNG
> 	select CRYPTO_USER_API
> 	help
> 	  This option enables the user-spaces interface for random
> 	  number generator algorithms.
> ...
> ```
> 
> These changes should then make getrawentropy actually return something since
> the the other test interface would be available and I could use it with the
> `-f` command line option of getrawentropy?

I fail to understand so far what exactly you try to achieve. The Jitter RNG is 
tested / validated completely separated from the LRNG as it is a completely 
standalone entropy source. The LRNG makes use of it, but for validation, the 
LRNG tools are not usable.

The LRNG tools are only usable for testing the LRNG-internal entropy sources 
of the IRQ-based or Scheduler-based entropy sources.

Now, if you want to test and validate the Jitter RNG, you must take the code 
found in [1]. Depending on the version you find in crypto/jitterentropy.c you 
need the following for gathering raw data:

- 2.2.0: [1]/tests/raw-entropy/recording_runtime_kernelspace/attic/

- 3.4.0: [1]/tests/raw-entropy/recording_*_kernelspace

Check the README.md files in these directories.

[1] https://github.com/smuellerDD/jitterentropy-library/

> 
> Sorry again if this is not the right location for all these questions. But
> (I think) I should be able to make my way forward after this since all that
> would be left for me to do was adapt the code for init.d instead of
> systemd.
> 
> Thank you so much for your time!


Ciao
Stephan
