### ISSUE TITLE
[Question] Imputing meaning from directory names

### ISSUE THREAD

**Issue by BruceMc-wg** [smuellerDD/lrng#31]
Hi Stephan,

My work has asked me to add LNRG to our 4.14.140 kernel that runs on our embedded devices. In looking through the repository and reading past issue tickets I have some questions.

- In the various version directories in the backports directory, there are directories of patches arranged by \<lnrg version\>-\<kernel version\>.
Up to lnrg version v45, there is a v45-4.14 directory of patches. There is also a directory of patches named v45-4.14.286.
After v45 we are seeing kernel versions for 4.14 like this
v46-4.14.286
v47-4.14.295
v48-4.14.302
v49-4.14.307
v50-4.14.314
v50-4.14.320

  - Am I correct in understanding that the kernel version in the directory name is the minimum versions that the directory's patches can be applied to? For example, I could apply patches to my 4.14.140 kernel from the v45-4.14 directory but not from the v45-4.14.286 directory?

  - If, for v45, I can only apply patches from the the v45-4.14 directory then does that mean I can only apply update to v45 since my 4.14.140 kernel version is not high enough to apply the patches from the 4.14.nnn directories in later lnrg versions?

- Another question, many of the patch files in the v45-4.14 directory show they are patching files from later linux kernel versions. Does this mean I will need to copy those base files from the later kernel version into my 4.14.140 kernel tree before applying the patches to them?

Thanks,

Bruce

**Comment by smuellerDD** [comment]
Am Donnerstag, 13. Juli 2023, 05:57:40 CEST schrieb Bruce McPeek:

Hi Bruce,

> Hi Stephan,
> 
> My work has asked me to add LNRG to our 4.14.140 kernel that runs on our
> embedded devices. In looking through the repository and reading past issue
> tickets I have some questions.
> 
> - In the various version directories in the backports directory, there are
> directories of patches arranged by \<lnrg version\>-\<kernel version\>. Up
> to lnrg version v45, there is a v45-4.14 directory of patches. There is
> also a directory of patches named v45-4.14.286. After v45 we are seeing
> kernel versions for 4.14 like this v46-4.14.286
> v47-4.14.295
> v48-4.14.302
> v49-4.14.307
> v50-4.14.314
> v50-4.14.320

You *should* (in the sense I have not run it myself) be able to use the v50 
patch series. Though, it is possible that some patches may not apply. Let me 
know and I could port them to your kernel.
> 
>   - Am I correct in understanding that the kernel version in the directory
> name is the minimum versions that the directory's patches can be applied
> to? For example, I could apply patches to my 4.14.140 kernel from the
> v45-4.14 directory but not from the v45-4.14.286 directory?

The versions just indicate which kernels have been used to test the patches 
against. That said, it should work for other kernels, but I do not give any 
guarantee. The patches may not apply cleanly for those other kernels.

> 
>   - If, for v45, I can only apply patches from the the v45-4.14 directory
> then does that mean I can only apply update to v45 since my 4.14.140 kernel
> version is not high enough to apply the patches from the 4.14.nnn
> directories in later lnrg versions?

First, I would recommend to use the newer one, v50.

Anyhow, the v45 or v50 references at the kernel backport directories indicate 
for which LRNG patch series these backport patches are intended for. The key 
idea is that the LRNG patches can be used *unmodified* as is when using these 
backport patches.

To perform that, do:

1. apply the backport patches with the 6-digit numbers

2. apply the associated LRNG patches

3. apply the backport patches with the 2-digit numbers
> 
> - Another question, many of the patch files in the v45-4.14 directory show
> they are patching files from later linux kernel versions. Does this mean I
> will need to copy those base files from the later kernel version into my
> 4.14.140 kernel tree before applying the patches to them?

Which files do you refer to? The patch strategy outlined above is applicable.
> 
> Thanks,
> 
> Bruce


Ciao
Stephan
