### ISSUE TITLE
Implementation of LNRG

### ISSUE THREAD

**Issue by Ricky-Tigg** [smuellerDD/lrng#34]
- **current version:** v.52 | Linux kernel v.6.6
- **my kernel:** 6.6.2-201.fc39.x86_64 GNU/Linux | Fedora

Hello. I assume this project covers the possibilities of use in a physical and virtual machine, e.g. for the latter, running on the QEMU-KVM platform in the _qcow2_ image file format. As per the documentation's instructions, the _lrng_presentation_v<version_number>.pdf_ file with the highest version number and this repository's directory tree, I could not conclude the methodology involved to put this project into practise in order to get added the LNRG component into my Linux distribution's Linux kernel. I interpreted that LNRG is a component **of your own**, thus that you developed; am I wrong?

Observations:
- In section https://github.com/smuellerDD/lrng#references; _doc/lrng.pdf_ | Developer is known to be a rigorous creature; therefore you are likely to prefer to present a correct syntax; _lrng-v<version_number>.pdf_. Otherwise there is not such a file there as _lrng.pdf_.
- In _doc/_ | Not each release version number is mentioned as part of the existing _lrng-v<version_number>.pdf_ and _lrng_presentation_v<version_number>.pdf_ file names. When so happens for a current release version, unknown is whether the closest existing prior version is valid documentation source.

_Side note:_ As it appears in the section _Document properties_ of each downloaded document that is in the **PDF format** and provided in this _doc_ directory, the **linearisation** feature, a.k.a. _Fast Web View_ is not implemented. Nonetheless while viewed on this platform, each of these documents behaves as if this feature was implemented into it by exhibiting at the bottom of some of the pages a <kbd>_more pages_</kbd> click-element. From my investigation I could conclude that it is the consequence of a built-in feature of this platform. Though are you able to tell me whether my conclusion is erroneous or correct?

**Comment by smuellerDD** [comment]
Am Dienstag, 28. November 2023, 14:30:36 CET schrieb Ricky-Tigg:

Hi Ricky-Tigg,

> - **current version:** v.52 | Linux kernel v.6.6
> - **my kernel:** 6.6.2-201.fc39.x86_64 GNU/Linux | Fedora
> 
> Hello. I assume this project covers the possibilities of use in a physical
> and virtual machine, e.g. for the latter, running on the QEMU-KVM platform
> in the _qcow2_ image file format.

Yes, both types of environments are clearly supported.

> As per the documentation's instructions,
> the _lrng_presentation_v<version_number>.pdf_ file with the highest version
> number and this repository's directory tree, I could not conclude the
> methodology involved to put this project into practise in order to get
> added the LNRG component into my Linux distribution's Linux kernel. I
> interpreted that LNRG is a component **of your own**, thus that you
> developed; am I wrong?

This is a patch series that you need to add to the kernel and then recompile 
the code. Fedora does not include this patch series.

If you want to have the same experience, but without kernel changes, use the 
ESDM - github.com/smuellerDD/esdm
> 
> Observations:
> - In section https://github.com/smuellerDD/lrng#references; _doc/lrng.pdf_ |
> Developer is known to be a rigorous creature; therefore you are likely to
> prefer to present a correct syntax; _lrng-v<version_number>.pdf_. Otherwise
> there is not such a file there as _lrng.pdf_.

Ok, changed.

> - In _doc/_ | Not each
> release version number is mentioned as part of the existing
> _lrng-v<version_number>.pdf_ and _lrng_presentation_v<version_number>.pdf_
> file names. When so happens for a current release version, unknown is
> whether the closest existing prior version is valid documentation source.

Sure, -v52 documentation is just coming, maybe tonight.
> 
> _Side note:_ As it appears in the section _Document properties_ of each
> downloaded document that is in the **PDF format** and provided in this
> _doc_ directory, the **linearisation** feature, a.k.a. _Fast Web View_ is
> not implemented. Nonetheless while viewed on this platform, each of these
> documents behaves as if this feature was implemented into it by exhibiting
> at the bottom of some of the pages a <kbd>_more pages_</kbd> click-element.
> From my investigation I could conclude that it is the consequence of a
> built-in feature of this platform. Though are you able to tell me whether
> my conclusion is erroneous or correct?

Not sure what you refer to. These are simple PDF pages as I do not plan to 
distribute the source files for the PDF.


Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. November 2023, 11:39:44 CET schrieb Ricky-Tigg:

Hi Ricky-Tigg,

> I would not even guess how to start getting any experience by reading the
> documents provided. I discover that no instructions to execute in
> command-line are present to achieve the goal you present; Nonetheless I
> suppose they are not meant to be such documents, as I am convinced that
> nobody would create a non-sense project. It might be worth observing your
> recommendation in respect to ESDM since at least that project exhibits some
> instructions.

Sorry, either you know how patches given in https://github.com/smuellerDD/
lrng/tree/master/kernel_patches/v6.6 are applied and you compile a kernel or 
not. If you would not know it, I am not sure it is wise that you handle those 
patches as it entails (a) compilation of the kernel with associated kernel 
configuration, (b) configuration of the LRNG options, and (c) installation of 
the kernel and get it to run in your system.

Ciao
Stephan
