### ISSUE TITLE
PDF Typo: Auxillery Poo 💩

### ISSUE THREAD

**Issue by catleeball** [smuellerDD/lrng#4]
In section 2.8 "LRNG-external Noise Sources", on page 31, it looks like there's a small typo.

"The data is injected into the auxiliary poo by hashing the input data..."

Assuming "poo" should be "pool". :slightly_smiling_face:

**Comment by smuellerDD** [comment]
Am Sonntag, 31. Januar 2021, 09:04:42 CET schrieb Lee Ball:

Hi Lee,

> In section 2.8 "LRNG-external Noise Sources", on page 31, it looks like
> there's a small typo.
> 
> "The data is injected into the auxiliary poo by hashing the input data..."
> 
> Assuming "poo" should be "pool". :slightly_smiling_face:

Thanks, fixed.

Ciao
Stephan
