### ISSUE TITLE
Possible to replace default DRNG (ChaCha20) from the get-go without LRNG_DRBG?

### ISSUE THREAD

**Issue by jancheta** [smuellerDD/lrng#40]
Hello! I have incorporated LRNG into openWRT with kernel version 4.4.60 and we are going for FIPS 140-3 Level 2 Validation. Because of the old kernel version, I am stuck on an older version of LRNG (`v43`).

I have built CONFIG_LRNG_DRBG in and get (lrng-related) kernel messages at boot up:
```
[    0.000000] lrng_drng: ChaCha20 core initialized with first seeding
[    7.256800] lrng_selftest: LRNG self-tests passed
[    7.257489] lrng_es_mgr: LRNG fully operational
[    7.260569] lrng_es_mgr: LRNG fully seeded with 160 bits of entropy
[    8.722881] lrng_drbg: DRBG with hmac(sha512) core allocated
[    8.732240] lrng_kcapi_hash: Hash sha512 allocated
[    8.737941] lrng_switch: Entropy pool read-hash allocated for DRNG for NUMA node 0
[    8.742452] lrng_switch: DRNG of NUMA node 0 switched
```

Building CONFIG_LRNG_DRBG as a module and autoloading it on boot doesnt change much, it only delays the `lrng_drbg` messages (and the ones after it) ~2 seconds.

LRNG related kernel configs
```
# zcat /proc/config.gz | grep -i LRNG
CONFIG_LRNG=y
# CONFIG_LRNG_OVERSAMPLE_ENTROPY_SOURCES is not set
CONFIG_LRNG_OVERSAMPLE_ES_BITS=0
CONFIG_LRNG_SEED_BUFFER_INIT_ADD_BITS=0
# CONFIG_LRNG_IRQ is not set
CONFIG_LRNG_RCT_CUTOFF=31
CONFIG_LRNG_APT_CUTOFF=325
CONFIG_LRNG_JENT=y
CONFIG_LRNG_JENT_ENTROPY_RATE=256
# CONFIG_LRNG_CPU is not set
CONFIG_LRNG_CPU_FULL_ENT_MULTIPLIER=1
CONFIG_LRNG_DRNG_SWITCH=y
CONFIG_LRNG_KCAPI_HASH=y
CONFIG_LRNG_DRBG=y
# CONFIG_LRNG_TESTING_MENU is not set
CONFIG_LRNG_SELFTEST=y
# CONFIG_LRNG_SELFTEST_PANIC is not set
```

Our FIPS consultant has mentioned that `For FIPS purposes,ChaCha20 should not be used with your DRBG for any cryptographic purpose, including DRBG initialization/instantiation, self-testing, or key generation` and `The important thing is that none of those functions happen using ChaCha20 for FIPS purposes. Your question regarding timing is not really a FIPS question, but I would suggest you keep the time down to a minimum. As it stands, having ChaCha20 active in the module at all could now potentially require an update to the documentation to include ChaCha20 as a "non-Approved algorithm in Approved mode with no security claimed"`. I am working to see if this even feasible and wondering if you had any advice you could offer. Because the switch happens so early in boot I do not believe it is used for anything before the switch. And I assume it goes through the appropriate initialization, instantiation, and self-testing. We also are running the kernel in `fips` mode.

Maybe I am missing something simple though too. Any help would be greatly appreciated!

**Comment by smuellerDD** [comment]
Am Montag, 16. Dezember 2024, 23:47:45 Mitteleuropäische Normalzeit schrieb 
jancheta:

Hi jancheta,

> Hello! I have incorporated LRNG into openWRT with kernel version 4.4.60 and
> we are going for FIPS 140-3 Level 2 Validation. Because of the old kernel
> version, I am stuck on an older version of LRNG (`v43`).

ok, but please note that after v43, some FIPS relevant changes went in as 
outlined in the change log considering IG D.K.

But anyhow.
> 
> I have built CONFIG_LRNG_DRBG in and get (lrng-related) kernel messages at
> boot up: ```
> [    0.000000] lrng_drng: ChaCha20 core initialized with first seeding
> [    7.256800] lrng_selftest: LRNG self-tests passed
> [    7.257489] lrng_es_mgr: LRNG fully operational
> [    7.260569] lrng_es_mgr: LRNG fully seeded with 160 bits of entropy
> [    8.722881] lrng_drbg: DRBG with hmac(sha512) core allocated
> [    8.732240] lrng_kcapi_hash: Hash sha512 allocated
> [    8.737941] lrng_switch: Entropy pool read-hash allocated for DRNG for
> NUMA node 0 [    8.742452] lrng_switch: DRNG of NUMA node 0 switched
> ```

Looks as expected.

What is your concern?
> 
> Building CONFIG_LRNG_DRBG as a module and autoloading it on boot doesnt
> change much, it only delays the `lrng_drbg` messages (and the ones after
> it) ~2 seconds.
> 
> LRNG related kernel configs
> ```
> # zcat /proc/config.gz | grep -i LRNG
> CONFIG_LRNG=y
> # CONFIG_LRNG_OVERSAMPLE_ENTROPY_SOURCES is not set
> CONFIG_LRNG_OVERSAMPLE_ES_BITS=0
> CONFIG_LRNG_SEED_BUFFER_INIT_ADD_BITS=0
> # CONFIG_LRNG_IRQ is not set
> CONFIG_LRNG_RCT_CUTOFF=31
> CONFIG_LRNG_APT_CUTOFF=325
> CONFIG_LRNG_JENT=y
> CONFIG_LRNG_JENT_ENTROPY_RATE=256
> # CONFIG_LRNG_CPU is not set
> CONFIG_LRNG_CPU_FULL_ENT_MULTIPLIER=1
> CONFIG_LRNG_DRNG_SWITCH=y
> CONFIG_LRNG_KCAPI_HASH=y
> CONFIG_LRNG_DRBG=y
> # CONFIG_LRNG_TESTING_MENU is not set
> CONFIG_LRNG_SELFTEST=y
> # CONFIG_LRNG_SELFTEST_PANIC is not set
> ```
> 
> Our FIPS consultant has mentioned that `For FIPS purposes,ChaCha20 should
> not be used with your DRBG for any cryptographic purpose, including DRBG
> initialization/instantiation, self-testing, or key generation`

Naturally, but this applies to any use cases FIPS cares about. Those use cases 
come to life when user space starts. Thus, the switch to the FIPS compliant 
algos must happen before user space starts. With the static compilation of the 
algos, that is ensured - see the dmesg in relation to when user space starts.

> and `The
> important thing is that none of those functions happen using ChaCha20 for
> FIPS purposes. Your question regarding timing is not really a FIPS
> question, but I would suggest you keep the time down to a minimum. As it
> stands, having ChaCha20 active in the module at all could now potentially
> require an update to the documentation to include ChaCha20 as a
> "non-Approved algorithm in Approved mode with no security claimed"`

It has to be. There is no technical way to allocate the DRBG right from the 
start, because

1. the kernel crypto API is not present in early boot

2. the kernel crypto API implementation may sleep, so in-kernel users in the 
atomic code path cannot use a kernel crypto API algo


> . I am
> working to see if this even feasible and wondering if you had any advice
> you could offer.

ChaCha20 must stay as there is no replacement for it short of using my 
leancrypto kernel module that provides a DRBG that is can be used in early 
boot and atomic contexts. But integrating that may be a bit of stretch for 
which I do not see the need.

Simply document that there is a non-approved algo, but it is not used for FIPS 
contexts.

> Because the switch happens so early in boot I do not
> believe it is used for anything before the switch.

It certainly may: KASLR (ok, not in 4.4), hash table init, other book keeping. 

> And I assume it goes
> through the appropriate initialization, instantiation, and self-testing. We
> also are running the kernel in `fips` mode.
> 
> Maybe I am missing something simple though too. Any help would be greatly
> appreciated!


Ciao
Stephan

**Comment by jancheta** [comment]
Appreciate the response Stephan.

Forgive any of my questions that dont make sense since I am still fairly new and learning more about the kernel in general.

I will take a look at the changelog to see if there is something that we would need to look at. Im unsure though how much we would be able to do. A kernel upgrade isnt something we can do at this stage which restricts any upgrade to LRNG as well.

Thanks again!
Justin
