### ISSUE TITLE
How to add lrng to kernel?

### ISSUE THREAD

**Issue by MysteriousLog6** [smuellerDD/lrng#6]
Kind of a dumb question! 
Pretty new to Linux kernel development , could you please explain how to add lrng to linux 4.4 source? I am very confused at the moment as (This is a me problem) I couldn't find documentation about this.

**Comment by smuellerDD** [comment]
Am Montag, dem 26.07.2021 um 07:28 -0700 schrieb Mysteriouslog6:
> Kind of a dumb question! 
> Pretty new to Linux kernel development , could you please explain how to add
> lrng to linux 4.4 source? I am very confused at the moment as (This is a me
> problem) I couldn't find documentation about this.

If you plan to take the latest patch series v41, please see the readme in
https://github.com/smuellerDD/lrng/tree/master/backports/v41-4.4

1. Apply v41-00000*.patch

2. Apply the LRNG patches from
https://github.com/smuellerDD/lrng/tree/master/kernel_patches/v5.13

3. Apply the two-digit patches v41-??-*.patch

Ciao
Stephan

**Comment by MysteriousLog6** [comment]
I had done all of this except for the patches from v5.13! Will try now

**Comment by MysteriousLog6** [comment]
When you say "LRNG" patches do you also mean the "41-0001-Linux-Random-Number-Generator.patch" with the other patches that have LRNG in the name?

**Comment by smuellerDD** [comment]
Am Montag, dem 26.07.2021 um 08:14 -0700 schrieb Mysteriouslog6:
> When you say "LRNG" patches do you also mean the "41-0001-Linux-Random-
> Number-Generator.patch" with the other patches that have LRNG in the name?
> 

Sure, those are THE LRNG patches - the others in the v4.4 backports directory
just massage the code so that the real patches fit to the kernel.

Ciao
Stephan

**Comment by MysteriousLog6** [comment]
So all patches in the directory? including the crypto patches?

**Comment by smuellerDD** [comment]
Am Montag, dem 26.07.2021 um 08:20 -0700 schrieb Mysteriouslog6:
> So all patches in the directory? including the crypto patches?

All patches in
https://github.com/smuellerDD/lrng/tree/master/kernel_patches/v5.13 in order
to get all options documented.

Ciao
Stephan
>

**Comment by MysteriousLog6** [comment]
Thanks!

**Comment by MysteriousLog6** [comment]
Which config do you use to enable it?

**Comment by smuellerDD** [comment]
Am Montag, dem 26.07.2021 um 21:04 -0700 schrieb Mysteriouslog6:
> Which config do you use to enable it?
> 

Device Drivers -> Character Devices -> Linux Random Number Generator

The options beneath enable various features. A configuration close to the
features of the legacy /dev/random code is achieved when not selecting any
subsequent option.

Ciao
Stephan

**Comment by MysteriousLog6** [comment]
Will try!

**Comment by MysteriousLog6** [comment]
Nvm , the options don't seem to exist.

**Comment by smuellerDD** [comment]
Am Dienstag, 27. Juli 2021, 07:34:31 CEST schrieb Mysteriouslog6:

Hi Mysteriouslog6,

> Nvm , the options don't seem to exist.

Then you did not patch the kernel as suggested.

Ciao
Stephan

**Comment by MysteriousLog6** [comment]
I did do all the patches as suggested , it is in this commit: https://github.com/MysteriousLog6/Elixir/commit/b961d2866a06913e9f71cba91d76c60ab705ea11

**Comment by smuellerDD** [comment]
Am Montag, dem 26.07.2021 um 22:41 -0700 schrieb Mysteriouslog6:
> I did do all the patches as suggested , it is in this commit:
> https://github.com/MysteriousLog6/Elixir/commit/b961d2866a06913e9f71cba91d76c60ab705ea11
> 

Maybe so, but the patches were not applied correctly -
https://github.com/MysteriousLog6/Elixir/blob/eas/drivers/char/Kconfig does
not contain the end

```
source "drivers/char/lrng/Kconfig"
```

It seems your kernel code has more patches - everything below 

```
source "drivers/char/xillybus/Kconfig"
```

does not seem to be in the stock kernel. Thus it is very likely you got an
error during applying the patches.

Anyway, if you ad the aforementioned line, the option becomes available.

Ciao
Stephan

**Comment by MysteriousLog6** [comment]
Will check! Thanks for helping , sorry for wasting your time!!

**Comment by MysteriousLog6** [comment]
Is it possible that I can check that lrng has indeed been
properly installed? In the kernel?

**Comment by smuellerDD** [comment]
Am Dienstag, dem 27.07.2021 um 00:48 -0700 schrieb Mysteriouslog6:
> Is it possible that I can check that lrng has indeed been
> properly installed? In the kernel?

Yes: by verifying that there are no failures during applying the patches. Only
offsets of the hunks are possible.

Ciao
Stephan
>
