### ISSUE TITLE
Support for kernel 5.17

### ISSUE THREAD

**Issue by sirlucjan** [smuellerDD/lrng#9]
Do you plan to add support for kernel 5.17? Unfortunately, the patches do not apply correctly.

**Comment by smuellerDD** [comment]
Am Dienstag, 15. März 2022, 16:43:12 CET schrieb Piotr Górski:

Hi Piotr,

> Do you plan to add support for kernel 5.17? Unfortunately, the patches do
> not apply correctly.

Yes, I plan that - the patches are already available and when 5.17 comes out I 
will have the update ready.

Ciao
Stephan

**Comment by sirlucjan** [comment]
I'm very happy about that. Thanks!
